import type { ComponentType } from 'react';
import { Network, Layers, Globe, ShieldCheck, Server } from 'lucide-react';

export interface Topic {
  id: string;
  name: string;
  description: string;
  icon: ComponentType<{ className?: string }>;
}

export const topics: Topic[] = [
  {
    id: 'conceitos-basicos',
    name: 'Conceitos Básicos de Rede',
    description: 'Tipos de rede (LAN, WAN), topologias e hardware essencial como cabos e NICs.',
    icon: Network,
  },
  {
    id: 'modelos-osi-tcpip',
    name: 'Modelo OSI e TCP/IP',
    description: 'Entenda as camadas dos modelos de referência que governam a comunicação de rede.',
    icon: Layers,
  },
  {
    id: 'enderecamento-ip',
    name: 'Endereçamento IP e Sub-redes',
    description: 'Domine o endereçamento IPv4/IPv6, máscaras de sub-rede e o cálculo de redes.',
    icon: Globe,
  },
  {
    id: 'protocolos-essenciais',
    name: 'Protocolos Essenciais',
    description: 'Aprenda sobre TCP, UDP, HTTP, DNS, DHCP e outros protocolos chave.',
    icon: Server,
  },
  {
    id: 'seguranca-de-rede',
    name: 'Segurança de Rede',
    description: 'Explore os princípios de firewalls, VPNs, criptografia e políticas de segurança.',
    icon: ShieldCheck,
  },
];

export interface Question {
  id: number;
  topicId: string;
  question: string;
  options: string[];
  answer: number;
  explanation: string;
}

export interface ClientTopic {
  id: string;
  name:string;
  description: string;
}


export function getIconForTopic(topicId: string): ComponentType<{ className?: string }> {
  const topic = topics.find(t => t.id === topicId);
  return topic ? topic.icon : () => null;
}

export const questions: Question[] = [
  // Conceitos Básicos de Rede - 20 questions
  {
    id: 1,
    topicId: 'conceitos-basicos',
    question: 'Qual topologia de rede conecta todos os dispositivos a um ponto central, como um switch?',
    options: ['Anel', 'Barramento', 'Estrela', 'Malha'],
    answer: 2,
    explanation: 'Na topologia em estrela, todos os dispositivos são conectados a um hub ou switch central. Falhas em um link afetam apenas um dispositivo, mas uma falha no ponto central paralisa a rede.',
  },
  {
    id: 2,
    topicId: 'conceitos-basicos',
    question: 'O que significa a sigla LAN?',
    options: ['Large Area Network', 'Local Area Network', 'Logical Area Network', 'Long Area Network'],
    answer: 1,
    explanation: 'LAN significa Local Area Network (Rede de Área Local). É uma rede que abrange uma área geográfica pequena, como um escritório, casa ou um prédio.',
  },
  {
    id: 3,
    topicId: 'conceitos-basicos',
    question: 'Qual tipo de cabo é mais comumente usado em redes Ethernet modernas?',
    options: ['Cabo Coaxial', 'Fibra Óptica', 'Par Trançado (UTP/STP)', 'Cabo Serial'],
    answer: 2,
    explanation: 'O cabo de Par Trançado, especialmente o UTP (Unshielded Twisted Pair) Cat 5e e Cat 6, é o padrão para conexões Ethernet com fio devido ao seu custo-benefício e desempenho.',
  },
  {
    id: 4,
    topicId: 'conceitos-basicos',
    question: 'Um dispositivo que opera na Camada 1 e simplesmente repete o sinal para todas as portas é um:',
    options: ['Switch', 'Roteador', 'Hub', 'Bridge'],
    answer: 2,
    explanation: 'Um hub é um dispositivo da Camada Física (Camada 1) que retransmite todos os dados recebidos para todas as suas portas, criando um único domínio de colisão.',
  },
  {
    id: 5,
    topicId: 'conceitos-basicos',
    question: 'Qual dispositivo é necessário para conectar uma LAN à Internet?',
    options: ['Switch', 'Roteador', 'Repetidor', 'Access Point'],
    answer: 1,
    explanation: 'Um roteador é usado para conectar redes diferentes, como a sua rede local (LAN) e a rede de área ampla (WAN) da Internet. Ele direciona o tráfego entre essas redes.',
  },
  {
    id: 6,
    topicId: 'conceitos-basicos',
    question: 'O que é uma WAN?',
    options: ['Uma rede dentro de um único prédio', 'Uma rede sem fio', 'Uma rede que conecta dispositivos via Bluetooth', 'Uma rede que abrange uma grande área geográfica, como cidades ou países'],
    answer: 3,
    explanation: 'WAN significa Wide Area Network (Rede de Área Ampla). Ela interliga múltiplas LANs que podem estar em diferentes cidades, estados ou até continentes.',
  },
  {
    id: 7,
    topicId: 'conceitos-basicos',
    question: 'Qual é a função de uma Placa de Rede (NIC)?',
    options: ['Armazenar arquivos da rede', 'Fornecer a interface física e de enlace para um computador se conectar a uma rede', 'Apenas modular o sinal de internet', 'Bloquear vírus'],
    answer: 1,
    explanation: 'A NIC (Network Interface Card) é o hardware que permite a um computador ou dispositivo se conectar a uma rede. Ela possui um endereço MAC único.',
  },
  {
    id: 8,
    topicId: 'conceitos-basicos',
    question: 'Na topologia de barramento (bus), como os dispositivos são conectados?',
    options: ['A um ponto central', 'Em um círculo fechado', 'A um único cabo principal (backbone)', 'Todos conectados a todos'],
    answer: 2,
    explanation: 'Na topologia de barramento, todos os dispositivos compartilham um único cabo. Embora simples e barata, uma falha no cabo principal pode derrubar toda a rede.',
  },
  {
    id: 9,
    topicId: 'conceitos-basicos',
    question: 'Qual topologia oferece a maior redundância, mas é também a mais cara?',
    options: ['Estrela', 'Barramento', 'Anel', 'Malha Completa (Full Mesh)'],
    answer: 3,
    explanation: 'Em uma topologia de malha completa, cada dispositivo está conectado a todos os outros. Isso oferece múltiplos caminhos para os dados, garantindo alta redundância, mas o custo de cabeamento é muito alto.',
  },
  {
    id: 10,
    topicId: 'conceitos-basicos',
    question: 'A Internet é o maior exemplo de qual tipo de rede?',
    options: ['LAN', 'MAN', 'WAN', 'PAN'],
    answer: 2,
    explanation: 'A Internet é uma rede global que conecta bilhões de dispositivos em todo o mundo, sendo o maior e mais conhecido exemplo de uma WAN (Wide Area Network).',
  },
  {
    id: 11,
    topicId: 'conceitos-basicos',
    question: 'O que é "throughput" (vazão) em uma rede?',
    options: ['O atraso na transmissão de dados', 'A medida real da quantidade de dados transferida em um período', 'A capacidade máxima teórica de uma rede', 'O número de dispositivos conectados'],
    answer: 1,
    explanation: 'Throughput, ou vazão, é a taxa de transferência de dados real e medida em uma rede, que pode ser afetada por latência, congestionamento e outros fatores. É diferente da largura de banda, que é a capacidade teórica.',
  },
  {
    id: 12,
    topicId: 'conceitos-basicos',
    question: 'O que é latência?',
    options: ['A velocidade de download', 'O tempo que um pacote de dados leva para ir do remetente ao destinatário', 'A quantidade de dados que pode ser enviada', 'A segurança da conexão'],
    answer: 1,
    explanation: 'Latência, ou atraso (delay), é o tempo total que um pacote de dados leva para viajar de um ponto a outro na rede. É um fator crucial para o desempenho de aplicações em tempo real.',
  },
  {
    id: 13,
    topicId: 'conceitos-basicos',
    question: 'Um switch Layer 2 toma decisões de encaminhamento com base em quê?',
    options: ['Endereços IP', 'Endereços MAC', 'Nomes de Host', 'Portas TCP/UDP'],
    answer: 1,
    explanation: 'Um switch padrão opera na Camada 2 (Enlace de Dados) e usa endereços MAC (Media Access Control) para encaminhar quadros (frames) para a porta correta onde o dispositivo de destino está localizado.',
  },
  {
    id: 14,
    topicId: 'conceitos-basicos',
    question: 'Qual é a principal vantagem de um switch sobre um hub?',
    options: ['É mais barato', 'Reduz as colisões de tráfego, encaminhando dados apenas para a porta de destino', 'É mais fácil de instalar', 'Usa menos energia'],
    answer: 1,
    explanation: 'Um switch cria um domínio de colisão por porta, encaminhando o tráfego de forma inteligente apenas para o destinatário. Um hub, por outro lado, envia os dados para todas as portas, aumentando as colisões.',
  },
  {
    id: 15,
    topicId: 'conceitos-basicos',
    question: 'Qual destas opções descreve uma rede MAN?',
    options: ['Uma rede que conecta seus dispositivos pessoais, como celular e fone de ouvido.', 'Uma rede que conecta computadores em um único quarto.', 'Uma rede que interconecta vários prédios em uma cidade.', 'Uma rede que conecta diferentes países.'],
    answer: 2,
    explanation: 'Uma MAN (Metropolitan Area Network) é uma rede que abrange uma área geográfica maior que uma LAN, mas menor que uma WAN, como uma cidade ou um campus universitário grande.',
  },
  {
    id: 16,
    topicId: 'conceitos-basicos',
    question: 'O que é um "domínio de colisão"?',
    options: ['A área física onde os roteadores estão localizados', 'Uma seção da rede onde pacotes de dados podem colidir uns com os outros', 'O alcance de um sinal Wi-Fi', 'Uma lista de sites bloqueados'],
    answer: 1,
    explanation: 'Um domínio de colisão é um segmento de rede onde duas ou mais estações podem transmitir ao mesmo tempo, causando uma colisão. Switches ajudam a segmentar esses domínios.',
  },
  {
    id: 17,
    topicId: 'conceitos-basicos',
    question: 'Qual o modo de transmissão onde a comunicação pode ocorrer em ambas as direções, mas não simultaneamente?',
    options: ['Simplex', 'Half-duplex', 'Full-duplex', 'Multiplex'],
    answer: 1,
    explanation: 'Half-duplex permite a comunicação bidirecional, mas apenas uma direção de cada vez. Walkie-talkies são um exemplo clássico.',
  },
  {
    id: 18,
    topicId: 'conceitos-basicos',
    question: 'Qual o modo de transmissão que permite a comunicação simultânea em ambas as direções?',
    options: ['Simplex', 'Half-duplex', 'Full-duplex', 'Complex'],
    answer: 2,
    explanation: 'Full-duplex permite que dados sejam enviados e recebidos ao mesmo tempo, como em uma conversa telefônica. A maioria das conexões de rede modernas opera em full-duplex.',
  },
  {
    id: 19,
    topicId: 'conceitos-basicos',
    question: 'Fibra óptica transmite dados usando:',
    options: ['Sinais elétricos', 'Pulsos de luz', 'Ondas de rádio', 'Sinais de fumaça'],
    answer: 1,
    explanation: 'A fibra óptica usa pulsos de luz para transmitir dados, o que permite velocidades muito mais altas, maiores distâncias e imunidade a interferência eletromagnética em comparação com cabos de cobre.',
  },
  {
    id: 20,
    topicId: 'conceitos-basicos',
    question: 'Qual dispositivo sem fio é usado para conectar uma rede sem fio a uma rede com fio?',
    options: ['Repetidor Wi-Fi', 'Adaptador Wi-Fi', 'Roteador Wi-Fi', 'Access Point (Ponto de Acesso)'],
    answer: 3,
    explanation: 'Um Access Point (AP) funciona como uma ponte, conectando clientes de uma rede sem fio (WLAN) a uma rede com fio (LAN). Roteadores Wi-Fi domésticos geralmente têm um AP integrado.',
  },

  // Modelo OSI e TCP/IP - 20 questions
  {
    id: 21,
    topicId: 'modelos-osi-tcpip',
    question: 'Qual camada do modelo OSI é responsável pelo endereçamento lógico e roteamento?',
    options: ['Camada Física', 'Camada de Enlace de Dados', 'Camada de Rede', 'Camada de Transporte'],
    answer: 2,
    explanation: 'A Camada de Rede (Camada 3) é responsável pelo endereçamento lógico (endereços IP) e por determinar o melhor caminho para os pacotes viajarem entre redes (roteamento).',
  },
  {
    id: 22,
    topicId: 'modelos-osi-tcpip',
    question: 'Em qual camada do modelo OSI os switches operam?',
    options: ['Camada 1 (Física)', 'Camada 2 (Enlace de Dados)', 'Camada 3 (Rede)', 'Camada 4 (Transporte)'],
    answer: 1,
    explanation: 'Switches padrão (Layer 2) operam na Camada de Enlace de Dados, usando endereços MAC para encaminhar quadros para os dispositivos corretos dentro de uma mesma rede local.',
  },
  {
    id: 23,
    topicId: 'modelos-osi-tcpip',
    question: 'O TCP e o UDP são protocolos de qual camada?',
    options: ['Aplicação', 'Rede', 'Transporte', 'Enlace'],
    answer: 2,
    explanation: 'TCP (Protocolo de Controle de Transmissão) e UDP (Protocolo de Datagrama de Usuário) operam na Camada de Transporte (Camada 4), gerenciando a comunicação de ponta a ponta.',
  },
  {
    id: 24,
    topicId: 'modelos-osi-tcpip',
    question: 'A Camada de Apresentação (Camada 6) do modelo OSI é responsável por:',
    options: ['Roteamento de pacotes', 'Controle de fluxo', 'Formatação, criptografia e compressão de dados', 'Gerenciamento de sessão'],
    answer: 2,
    explanation: 'A Camada de Apresentação garante que os dados estejam em um formato utilizável e é onde a criptografia e a compressão de dados geralmente ocorrem.',
  },
  {
    id: 25,
    topicId: 'modelos-osi-tcpip',
    question: 'Qual é a PDU (Unidade de Dados de Protocolo) da Camada de Enlace de Dados?',
    options: ['Bit', 'Pacote', 'Quadro (Frame)', 'Segmento'],
    answer: 2,
    explanation: 'A PDU da Camada 2 é o Quadro (Frame). A camada de Rede usa Pacotes, e a camada de Transporte usa Segmentos (TCP) ou Datagramas (UDP).',
  },
  {
    id: 26,
    topicId: 'modelos-osi-tcpip',
    question: 'Qual camada do modelo TCP/IP corresponde às camadas de Aplicação, Apresentação e Sessão do modelo OSI?',
    options: ['Aplicação', 'Transporte', 'Internet', 'Acesso à Rede'],
    answer: 0,
    explanation: 'O modelo TCP/IP simplifica as coisas, combinando as funções das três camadas superiores do OSI em uma única camada chamada Aplicação.',
  },
  {
    id: 27,
    topicId: 'modelos-osi-tcpip',
    question: 'A Camada Física (Camada 1) lida com:',
    options: ['Endereçamento IP', 'Detecção de erros', 'Cabos, conectores e sinais elétricos', 'Nomes de domínio'],
    answer: 2,
    explanation: 'A Camada Física é responsável por todos os aspectos físicos da rede, como o tipo de cabeamento, voltagem dos sinais e pinagem dos conectores.',
  },
  {
    id: 28,
    topicId: 'modelos-osi-tcpip',
    question: 'O processo de adicionar cabeçalhos em cada camada à medida que os dados descem a pilha é chamado de:',
    options: ['Fragmentação', 'Encapsulamento', 'Desencapsulamento', 'Segmentação'],
    answer: 1,
    explanation: 'Encapsulamento é o processo de envolver os dados de uma camada superior com o cabeçalho da camada atual antes de passá-los para a camada inferior.',
  },
  {
    id: 29,
    topicId: 'modelos-osi-tcpip',
    question: 'Qual camada OSI é responsável por estabelecer, gerenciar e encerrar diálogos entre aplicações?',
    options: ['Transporte', 'Sessão', 'Apresentação', 'Aplicação'],
    answer: 1,
    explanation: 'A Camada de Sessão (Camada 5) gerencia a conversação (sessão) entre dois computadores, controlando o início, o fim e a manutenção do diálogo.',
  },
  {
    id: 30,
    topicId: 'modelos-osi-tcpip',
    question: 'Quantas camadas tem o modelo OSI?',
    options: ['4', '5', '7', '8'],
    answer: 2,
    explanation: 'O modelo OSI (Open Systems Interconnection) é um modelo de referência conceitual que possui 7 camadas, da Física à de Aplicação.',
  },
  {
    id: 31,
    topicId: 'modelos-osi-tcpip',
    question: 'O endereço MAC é um endereço de qual camada?',
    options: ['Camada 2 (Enlace)', 'Camada 3 (Rede)', 'Camada 4 (Transporte)', 'Camada 7 (Aplicação)'],
    answer: 0,
    explanation: 'O endereço MAC (Media Access Control) é o endereço físico da placa de rede e é usado na Camada de Enlace de Dados para comunicação dentro da mesma rede local.',
  },
  {
    id: 32,
    topicId: 'modelos-osi-tcpip',
    question: 'O modelo TCP/IP é um modelo __________ enquanto o modelo OSI é um modelo _________.',
    options: ['prático, conceitual', 'conceitual, prático', 'obsoleto, moderno', 'moderno, obsoleto'],
    answer: 0,
    explanation: 'O modelo TCP/IP foi desenvolvido para a ARPANET e se tornou o padrão prático da Internet. O modelo OSI foi desenvolvido como um modelo de referência teórico e é usado para ensino e padronização.',
  },
  {
    id: 33,
    topicId: 'modelos-osi-tcpip',
    question: 'Qual camada OSI garante a entrega de dados de ponta a ponta sem erros, em sequência e sem perdas ou duplicações?',
    options: ['Rede', 'Enlace', 'Sessão', 'Transporte'],
    answer: 3,
    explanation: 'A Camada de Transporte (Camada 4), através do protocolo TCP, é responsável pela entrega confiável de dados entre os processos de origem e destino.',
  },
  {
    id: 34,
    topicId: 'modelos-osi-tcpip',
    question: 'Roteadores operam principalmente em qual camada?',
    options: ['Camada 2 (Enlace)', 'Camada 3 (Rede)', 'Camada 4 (Transporte)', 'Camada 7 (Aplicação)'],
    answer: 1,
    explanation: 'Roteadores são dispositivos de Camada 3 que usam endereços IP para encaminhar pacotes entre redes diferentes.',
  },
  {
    id: 35,
    topicId: 'modelos-osi-tcpip',
    question: 'O que é a PDU da Camada de Rede?',
    options: ['Segmento', 'Datagrama', 'Quadro (Frame)', 'Pacote (Packet)'],
    answer: 3,
    explanation: 'A Unidade de Dados de Protocolo (PDU) da Camada 3 (Rede) é o Pacote (Packet).',
  },
  {
    id: 36,
    topicId: 'modelos-osi-tcpip',
    question: 'A camada do modelo TCP/IP responsável por endereçamento e roteamento é a:',
    options: ['Aplicação', 'Transporte', 'Internet', 'Acesso à Rede'],
    answer: 2,
    explanation: 'A camada de Internet do modelo TCP/IP (equivalente à camada de Rede do OSI) lida com o empacotamento, endereçamento e roteamento de pacotes.',
  },
  {
    id: 37,
    topicId: 'modelos-osi-tcpip',
    question: 'Qual das seguintes opções NÃO é uma camada do modelo OSI?',
    options: ['Camada de Internet', 'Camada de Sessão', 'Camada de Rede', 'Camada Física'],
    answer: 0,
    explanation: 'A "Camada de Internet" pertence ao modelo TCP/IP, não ao modelo OSI. O modelo OSI possui uma "Camada de Rede" em seu lugar.',
  },
  {
    id: 38,
    topicId: 'modelos-osi-tcpip',
    question: 'HTTP, FTP, SMTP e DNS são protocolos de qual camada?',
    options: ['Transporte', 'Rede', 'Enlace', 'Aplicação'],
    answer: 3,
    explanation: 'Todos esses são protocolos da camada de Aplicação, que fornecem serviços diretamente aos aplicativos do usuário final.',
  },
  {
    id: 39,
    topicId: 'modelos-osi-tcpip',
    question: 'O controle de acesso ao meio (MAC) é uma subcamada de qual camada OSI?',
    options: ['Física', 'Enlace de Dados', 'Rede', 'Transporte'],
    answer: 1,
    explanation: 'A camada de Enlace de Dados é frequentemente dividida em duas subcamadas: LLC (Logical Link Control) e MAC (Media Access Control), que lida com o acesso ao meio físico.',
  },
  {
    id: 40,
    topicId: 'modelos-osi-tcpip',
    question: 'O processo de remover cabeçalhos à medida que os dados sobem a pilha de protocolos é chamado de:',
    options: ['Encapsulamento', 'Multiplexação', 'Desencapsulamento', 'Rearranjo'],
    answer: 2,
    explanation: 'Desencapsulamento é o processo inverso do encapsulamento. Cada camada remove seu respectivo cabeçalho, interpreta as informações e passa os dados para a camada superior.',
  },

  // Endereçamento IP e Sub-redes - 20 questions
  {
    id: 41,
    topicId: 'enderecamento-ip',
    question: 'Qual é a máscara de sub-rede padrão para uma rede Classe C?',
    options: ['255.0.0.0', '255.255.0.0', '255.255.255.0', '255.255.255.255'],
    answer: 2,
    explanation: 'No sistema de classes (hoje obsoleto, mas ainda referenciado), as redes Classe C usavam uma máscara /24, que é 255.255.255.0.',
  },
  {
    id: 42,
    topicId: 'enderecamento-ip',
    question: 'Quantos endereços de host utilizáveis existem em uma sub-rede /28?',
    options: ['14', '16', '30', '32'],
    answer: 0,
    explanation: 'Um prefixo /28 deixa 32 - 28 = 4 bits para hosts. Isso dá 2^4 = 16 endereços totais. Subtraindo 2 (um para a rede, um para broadcast), restam 14 endereços utilizáveis.',
  },
  {
    id: 43,
    topicId: 'enderecamento-ip',
    question: 'Qual dos seguintes é um endereço IP privado (RFC 1918)?',
    options: ['172.32.10.5', '192.169.1.1', '10.1.2.3', '1.1.1.1'],
    answer: 2,
    explanation: 'Os blocos de endereços privados são 10.0.0.0/8, 172.16.0.0/12 e 192.168.0.0/16. O endereço 10.1.2.3 está dentro do primeiro bloco.',
  },
  {
    id: 44,
    topicId: 'enderecamento-ip',
    question: 'Qual é o endereço de broadcast da rede 192.168.1.128/25?',
    options: ['192.168.1.192', '192.168.1.254', '192.168.1.255', '192.168.1.0'],
    answer: 2,
    explanation: 'Uma rede /25 tem 128 endereços. A primeira sub-rede é 0-127, a segunda é 128-255. O endereço de broadcast é sempre o último endereço da sub-rede, que neste caso é 192.168.1.255.',
  },
  {
    id: 45,
    topicId: 'enderecamento-ip',
    question: 'O endereço 127.0.0.1 é usado para quê?',
    options: ['Broadcast', 'Loopback', 'Gateway Padrão', 'Servidor DNS'],
    answer: 1,
    explanation: '127.0.0.1 é o endereço de loopback, usado por um host para enviar pacotes a si mesmo, principalmente para testes de software e da pilha de rede.',
  },
  {
    id: 46,
    topicId: 'enderecamento-ip',
    question: 'O que é NAT (Network Address Translation)?',
    options: ['Um protocolo de roteamento', 'Um método para traduzir endereços IP privados em endereços IP públicos', 'Um tipo de criptografia', 'Um protocolo de segurança sem fio'],
    answer: 1,
    explanation: 'NAT é uma técnica usada por roteadores para permitir que vários dispositivos em uma rede privada compartilhem um único endereço IP público para acessar a Internet.',
  },
  {
    id: 47,
    topicId: 'enderecamento-ip',
    question: 'Um endereço IPv6 tem quantos bits?',
    options: ['32', '48', '64', '128'],
    answer: 3,
    explanation: 'Endereços IPv6 são compostos por 128 bits, oferecendo um espaço de endereçamento imensamente maior em comparação com os 32 bits do IPv4.',
  },
  {
    id: 48,
    topicId: 'enderecamento-ip',
    question: 'Qual é a notação CIDR para a máscara de sub-rede 255.255.240.0?',
    options: ['/18', '/20', '/22', '/24'],
    answer: 1,
    explanation: 'A máscara 255.255.240.0 em binário é 11111111.11111111.11110000.00000000. Isso corresponde a 8 + 8 + 4 = 20 bits de rede, portanto, a notação CIDR é /20.',
  },
  {
    id: 49,
    topicId: 'enderecamento-ip',
    question: 'Para qual finalidade o endereço 255.255.255.255 é usado?',
    options: ['Loopback', 'Broadcast na rede local', 'Gateway', 'Unicast'],
    answer: 1,
    explanation: 'O endereço 255.255.255.255 é o endereço de broadcast limitado, que envia uma mensagem para todos os hosts no mesmo segmento de rede local.',
  },
  {
    id: 50,
    topicId: 'enderecamento-ip',
    question: 'O que é APIPA (Automatic Private IP Addressing)?',
    options: ['Um endereço público fixo', 'Um protocolo de segurança', 'Um endereço que um host Windows se atribui quando não encontra um servidor DHCP', 'Um endereço IPv6'],
    answer: 2,
    explanation: 'Quando um dispositivo Windows está configurado para DHCP, mas não encontra um servidor, ele se autoatribui um endereço no intervalo 169.254.0.0/16. Isso é chamado de APIPA.',
  },
  {
    id: 51,
    topicId: 'enderecamento-ip',
    question: 'Qual é o primeiro endereço de host utilizável na rede 172.16.8.0/22?',
    options: ['172.16.8.0', '172.16.8.1', '172.16.7.255', '172.16.11.254'],
    answer: 1,
    explanation: 'O endereço de rede é 172.16.8.0. O primeiro endereço de host utilizável é sempre o endereço de rede mais um, ou seja, 172.16.8.1.',
  },
  {
    id: 52,
    topicId: 'enderecamento-ip',
    question: 'Como o endereço IPv6 fe80:0000:0000:0000:0a00:00ff:fe64:0001 pode ser abreviado?',
    options: ['fe80::a00:ff:fe64:1', 'fe80:0:0:0:a00:ff:fe64:1', 'fe80::0a00:ff:fe64:1', 'fe80:a:f:fe64:1'],
    answer: 0,
    explanation: 'A maior sequência contígua de zeros pode ser substituída por "::" (uma vez por endereço), e os zeros à esquerda em cada bloco de 16 bits podem ser omitidos.',
  },
  {
    id: 53,
    topicId: 'enderecamento-ip',
    question: 'Uma empresa precisa de 500 endereços de host em uma única sub-rede. Qual prefixo CIDR atenderia a essa necessidade?',
    options: ['/24', '/23', '/22', '/21'],
    answer: 2,
    explanation: 'Para 500 hosts, precisamos de 9 bits de host (2^9 = 512 endereços). 32 - 9 = 23. Uma máscara /23 fornece 510 hosts utilizáveis, o que é insuficiente. Uma /22 (10 bits de host, 1022 hosts) é necessária.',
  },
  {
    id: 54,
    topicId: 'enderecamento-ip',
    question: 'O que é o Gateway Padrão (Default Gateway)?',
    options: ['O endereço do seu computador', 'O endereço IP de um servidor web', 'O endereço do roteador que sua rede usa para se comunicar com outras redes', 'O endereço MAC da sua placa de rede'],
    answer: 2,
    explanation: 'O gateway padrão é o dispositivo (geralmente um roteador) para onde o tráfego é enviado quando o destino está em uma rede diferente da rede local.',
  },
  {
    id: 55,
    topicId: 'enderecamento-ip',
    question: 'O que é VLSM (Variable Length Subnet Mask)?',
    options: ['Usar a mesma máscara de sub-rede em toda a rede', 'Usar diferentes máscaras de sub-rede para otimizar o uso do espaço de endereçamento', 'Um tipo de endereço IPv6', 'Um protocolo de roteamento obsoleto'],
    answer: 1,
    explanation: 'VLSM permite que engenheiros de rede usem máscaras de sub-rede de diferentes tamanhos para diferentes sub-redes, o que permite uma alocação de endereços IP muito mais eficiente.',
  },
  {
    id: 56,
    topicId: 'enderecamento-ip',
    question: 'Qual é o ID da rede para o host 10.150.75.200/12?',
    options: ['10.144.0.0', '10.128.0.0', '10.0.0.0', '10.150.0.0'],
    answer: 0,
    explanation: 'Uma máscara /12 (255.240.0.0) tem um tamanho de bloco de 16 no segundo octeto. Os múltiplos são 0, 16, 32, ..., 128, 144, 160. O endereço 150 cai no bloco que começa em 144. Portanto, a rede é 10.144.0.0.',
  },
  {
    id: 57,
    topicId: 'enderecamento-ip',
    question: 'O que é um endereço unicast?',
    options: ['Um endereço que representa um único dispositivo na rede', 'Um endereço que representa um grupo de dispositivos', 'Um endereço que representa todos os dispositivos na rede', 'Um endereço usado para streaming'],
    answer: 0,
    explanation: 'Unicast é a comunicação um-para-um. Um pacote enviado para um endereço unicast é destinado a uma única interface de rede.',
  },
  {
    id: 58,
    topicId: 'enderecamento-ip',
    question: 'Endereços que começam com fe80:: são de que tipo em IPv6?',
    options: ['Global Unicast', 'Unique Local', 'Link-Local', 'Multicast'],
    answer: 2,
    explanation: 'Endereços no bloco fe80::/10 são endereços Link-Local. Eles são usados para comunicação na mesma rede local e não são roteáveis na internet.',
  },
  {
    id: 59,
    topicId: 'enderecamento-ip',
    question: 'Qual máscara de sub-rede empresta 3 bits de host para a rede a partir de uma rede Classe C padrão?',
    options: ['255.255.255.192', '255.255.255.224', '255.255.255.240', '255.255.255.248'],
    answer: 1,
    explanation: 'Uma Classe C padrão é /24. Emprestar 3 bits a torna uma /27. A máscara /27 em binário é ...11100000, que corresponde a 128+64+32 = 224. Portanto, 255.255.255.224.',
  },
  {
    id: 60,
    topicId: 'enderecamento-ip',
    question: 'A principal razão para a criação do IPv6 foi:',
    options: ['Aumentar a velocidade da internet', 'Esgotamento dos endereços IPv4', 'Simplificar as sub-redes', 'Melhorar a segurança do Wi-Fi'],
    answer: 1,
    explanation: 'O crescimento exponencial da Internet levou ao esgotamento do espaço de endereçamento do IPv4. O IPv6, com seus 128 bits, foi criado para resolver esse problema.',
  },

  // Protocolos Essenciais - 20 questions
  {
    id: 61,
    topicId: 'protocolos-essenciais',
    question: 'Qual protocolo da camada de transporte é não orientado à conexão e não garante a entrega?',
    options: ['TCP', 'UDP', 'IP', 'HTTP'],
    answer: 1,
    explanation: 'UDP (User Datagram Protocol) é um protocolo "fire-and-forget". Ele é rápido porque não tem a sobrecarga de estabelecer uma conexão ou confirmar a entrega, sendo ideal para aplicações como streaming e DNS.',
  },
  {
    id: 62,
    topicId: 'protocolos-essenciais',
    question: 'Qual protocolo é usado para atribuir endereços IP dinamicamente a dispositivos em uma rede?',
    options: ['DNS', 'HTTP', 'DHCP', 'SMTP'],
    answer: 2,
    explanation: 'DHCP (Dynamic Host Configuration Protocol) automatiza a configuração de rede, fornecendo a clientes um endereço IP, máscara de sub-rede, gateway padrão e servidor DNS.',
  },
  {
    id: 63,
    topicId: 'protocolos-essenciais',
    question: 'O protocolo usado para traduzir nomes de domínio (como www.google.com) em endereços IP é o:',
    options: ['ARP', 'DNS', 'DHCP', 'ICMP'],
    answer: 1,
    explanation: 'DNS (Domain Name System) funciona como a "lista telefônica" da internet, resolvendo nomes fáceis de lembrar em endereços IP numéricos que os computadores entendem.',
  },
  {
    id: 64,
    topicId: 'protocolos-essenciais',
    question: 'Qual porta o protocolo HTTP usa por padrão?',
    options: ['21', '25', '80', '443'],
    answer: 2,
    explanation: 'HTTP (Hypertext Transfer Protocol), o protocolo fundamental da web, opera na porta 80.',
  },
  {
    id: 65,
    topicId: 'protocolos-essenciais',
    question: 'O que o "three-way handshake" do TCP estabelece?',
    options: ['O fim de uma conexão', 'Uma conexão confiável entre cliente e servidor', 'A rota para um pacote', 'O endereço MAC de um dispositivo'],
    answer: 1,
    explanation: 'O processo de três vias (SYN, SYN-ACK, ACK) é como o TCP estabelece e sincroniza uma conexão antes que qualquer dado seja transferido, garantindo a confiabilidade.',
  },
  {
    id: 66,
    topicId: 'protocolos-essenciais',
    question: 'Qual protocolo é usado pelo comando "ping" para testar a conectividade?',
    options: ['TCP', 'UDP', 'ICMP', 'IGMP'],
    answer: 2,
    explanation: 'O utilitário "ping" usa o ICMP (Internet Control Message Protocol), enviando solicitações de eco e aguardando respostas de eco para verificar se um host está alcançável.',
  },
  {
    id: 67,
    topicId: 'protocolos-essenciais',
    question: 'Qual protocolo é usado para resolver um endereço IP para um endereço MAC em uma rede local?',
    options: ['DNS', 'DHCP', 'RARP', 'ARP'],
    answer: 3,
    explanation: 'ARP (Address Resolution Protocol) é usado para descobrir o endereço de hardware (MAC) associado a um determinado endereço IP na mesma rede.',
  },
  {
    id: 68,
    topicId: 'protocolos-essenciais',
    question: 'Qual protocolo é usado para enviar e-mails entre servidores?',
    options: ['POP3', 'IMAP', 'SMTP', 'HTTP'],
    answer: 2,
    explanation: 'SMTP (Simple Mail Transfer Protocol) é o protocolo padrão para "empurrar" (push) e-mails de um cliente para um servidor e para transferir e-mails entre servidores de e-mail.',
  },
  {
    id: 69,
    topicId: 'protocolos-essenciais',
    question: 'HTTPS é a versão segura do HTTP e usa qual porta por padrão?',
    options: ['80', '8080', '443', '22'],
    answer: 2,
    explanation: 'HTTPS (HTTP Secure) criptografa a comunicação HTTP usando TLS/SSL e opera na porta 443.',
  },
  {
    id: 70,
    topicId: 'protocolos-essenciais',
    question: 'Qual protocolo permite que você acesse e gerencie sua caixa de e-mail em um servidor, mantendo os e-mails no servidor?',
    options: ['POP3', 'SMTP', 'IMAP', 'SNMP'],
    answer: 2,
    explanation: 'IMAP (Internet Message Access Protocol) permite que os clientes acessem e manipulem e-mails diretamente no servidor, sincronizando o estado entre múltiplos dispositivos.',
  },
  {
    id: 71,
    topicId: 'protocolos-essenciais',
    question: 'FTP (File Transfer Protocol) usa duas conexões. Para que serve a porta 21?',
    options: ['Para transferência de dados', 'Para o canal de controle (comandos)', 'Para criptografia', 'Para encerrar a conexão'],
    answer: 1,
    explanation: 'No FTP, a porta 21 é usada para a conexão de controle, onde os comandos (como listar diretórios, enviar arquivo) são trocados. Uma porta separada (20 no modo ativo ou dinâmica no passivo) é usada para a transferência de dados real.',
  },
  {
    id: 72,
    topicId: 'protocolos-essenciais',
    question: 'Qual protocolo é usado para gerenciamento e monitoramento de dispositivos de rede?',
    options: ['NTP', 'SNMP', 'Telnet', 'RDP'],
    answer: 1,
    explanation: 'SNMP (Simple Network Management Protocol) é amplamente utilizado por administradores de rede para monitorar a saúde, o desempenho e a configuração de dispositivos como roteadores, switches e servidores.',
  },
  {
    id: 73,
    topicId: 'protocolos-essenciais',
    question: 'Qual é a principal vantagem do UDP sobre o TCP?',
    options: ['Garantia de entrega', 'Controle de congestionamento', 'Baixa sobrecarga (overhead) e velocidade', 'Ordenação de pacotes'],
    answer: 2,
    explanation: 'A simplicidade do UDP o torna muito mais rápido que o TCP, pois ele não precisa estabelecer uma conexão nem se preocupar com confirmações, tornando-o ideal para aplicações sensíveis ao tempo.',
  },
  {
    id: 74,
    topicId: 'protocolos-essenciais',
    question: 'Qual protocolo fornece acesso a um terminal remoto de forma segura e criptografada?',
    options: ['Telnet', 'SSH', 'RDP', 'FTP'],
    answer: 1,
    explanation: 'SSH (Secure Shell), que opera na porta 22, é o sucessor seguro do Telnet. Ele fornece uma conexão de linha de comando criptografada para administrar sistemas remotamente.',
  },
  {
    id: 75,
    topicId: 'protocolos-essenciais',
    question: 'O que o processo DORA representa no contexto do DHCP?',
    options: ['Data, Operation, Request, Acknowledge', 'Discover, Offer, Request, Acknowledge', 'Domain, Organization, Registration, Authority', 'Download, Open, Read, Assign'],
    answer: 1,
    explanation: 'DORA é o acrônimo para os quatro passos do processo DHCP: Discover (cliente procura por um servidor), Offer (servidor oferece um IP), Request (cliente solicita o IP oferecido) e Acknowledge (servidor confirma a atribuição).',
  },
  {
    id: 76,
    topicId: 'protocolos-essenciais',
    question: 'Qual protocolo é projetado para sincronizar relógios de computadores em uma rede?',
    options: ['TIME', 'DAYTIME', 'NTP', 'SNTP'],
    answer: 2,
    explanation: 'NTP (Network Time Protocol) é um protocolo robusto projetado para sincronizar com precisão os relógios de sistemas em uma rede com uma fonte de tempo de referência.',
  },
  {
    id: 77,
    topicId: 'protocolos-essenciais',
    question: 'Telnet é considerado inseguro porque:',
    options: ['É muito lento', 'Não está mais em desenvolvimento', 'Transmite todos os dados, incluindo senhas, em texto puro', 'Só funciona em sistemas Windows'],
    answer: 2,
    explanation: 'A principal falha de segurança do Telnet é que ele não possui criptografia, o que significa que qualquer pessoa que capture o tráfego pode ler tudo, inclusive nomes de usuário e senhas.',
  },
  {
    id: 78,
    topicId: 'protocolos-essenciais',
    question: 'Qual protocolo de roteamento é classificado como "link-state"?',
    options: ['RIP', 'EIGRP', 'OSPF', 'BGP'],
    answer: 2,
    explanation: 'OSPF (Open Shortest Path First) é um protocolo de roteamento do tipo link-state. Cada roteador constrói um mapa completo da topologia da rede para tomar decisões de roteamento.',
  },
  {
    id: 79,
    topicId: 'protocolos-essenciais',
    question: 'Qual é o protocolo usado para transferências de arquivos muito simples, sem autenticação, operando sobre UDP?',
    options: ['FTP', 'SFTP', 'SCP', 'TFTP'],
    answer: 3,
    explanation: 'TFTP (Trivial File Transfer Protocol) é uma versão muito simplificada do FTP. Por usar UDP e não ter autenticação, é frequentemente usado para inicializar dispositivos de rede (boot) ou transferir firmware.',
  },
  {
    id: 80,
    topicId: 'protocolos-essenciais',
    question: 'POP3 (Post Office Protocol 3) geralmente funciona de que maneira?',
    options: ['Sincroniza e-mails em vários dispositivos', 'Baixa os e-mails para o dispositivo local e os remove do servidor', 'Envia e-mails do cliente para o servidor', 'Arquiva e-mails na nuvem'],
    answer: 1,
    explanation: 'O comportamento padrão do POP3 é conectar-se ao servidor, baixar todas as mensagens para o cliente local e, em seguida, excluí-las do servidor. É um modelo "offline".',
  },

  // Segurança de Rede - 20 questions
  {
    id: 81,
    topicId: 'seguranca-de-rede',
    question: 'O que a "Confidencialidade" na tríade da CIA garante?',
    options: ['Que os dados não foram alterados', 'Que os dados estão disponíveis quando necessários', 'Que o acesso aos dados é restrito a pessoas não autorizadas', 'Que a origem dos dados é autêntica'],
    answer: 2,
    explanation: 'Confidencialidade é o princípio que visa impedir a divulgação não autorizada de informações. Criptografia é uma ferramenta comum para garantir a confidencialidade.',
  },
  {
    id: 82,
    topicId: 'seguranca-de-rede',
    question: 'O que é um firewall?',
    options: ['Um dispositivo que aumenta a velocidade da rede', 'Um sistema que monitora e controla o tráfego de rede com base em regras de segurança', 'Um antivírus para servidores', 'Um software para criar backups'],
    answer: 1,
    explanation: 'Um firewall atua como uma barreira entre uma rede confiável e uma não confiável (como a Internet), permitindo ou bloqueando o tráfego com base em um conjunto de regras.',
  },
  {
    id: 83,
    topicId: 'seguranca-de-rede',
    question: 'Qual tipo de ataque tenta sobrecarregar um servidor com tanto tráfego que ele não consegue mais responder a solicitações legítimas?',
    options: ['Phishing', 'Man-in-the-Middle', 'Ransomware', 'Negação de Serviço (DoS/DDoS)'],
    answer: 3,
    explanation: 'Um ataque de Negação de Serviço (Denial of Service - DoS) visa tornar um recurso de rede indisponível. Quando o ataque vem de várias fontes, é chamado de DDoS (Distributed DoS).',
  },
  {
    id: 84,
    topicId: 'seguranca-de-rede',
    question: 'O que é uma VPN (Virtual Private Network)?',
    options: ['Uma rede Wi-Fi pública', 'Uma conexão segura e criptografada sobre uma rede pública, como a Internet', 'Um tipo de firewall', 'Um protocolo para acelerar downloads'],
    answer: 1,
    explanation: 'Uma VPN cria um "túnel" criptografado através de uma rede insegura, permitindo que os dados viajem com segurança, como se estivessem em uma rede privada.',
  },
  {
    id: 85,
    topicId: 'seguranca-de-rede',
    question: 'Qual é o protocolo de segurança sem fio mais robusto e recomendado atualmente?',
    options: ['WEP', 'WPA', 'WPA2', 'WPA3'],
    answer: 3,
    explanation: 'WPA3 é o padrão mais recente e seguro, oferecendo proteção mais forte contra ataques de força bruta e criptografia mais robusta em comparação com seus predecessores (WPA2, WPA, WEP).',
  },
  {
    id: 86,
    topicId: 'seguranca-de-rede',
    question: 'Um ataque de Phishing é uma forma de:',
    options: ['Ataque de força bruta', 'Engenharia Social', 'Malware', 'Ataque de Negação de Serviço'],
    answer: 1,
    explanation: 'Phishing é uma técnica de engenharia social que engana os usuários para que eles revelem informações confidenciais (como senhas ou números de cartão de crédito) ao se disfarçar de uma entidade confiável.',
  },
  {
    id: 87,
    topicId: 'seguranca-de-rede',
    question: 'O que é uma DMZ (Zona Desmilitarizada) em uma rede?',
    options: ['Uma área da rede sem qualquer segurança', 'Uma sub-rede que fica entre a rede interna e a Internet, contendo servidores públicos', 'O núcleo mais seguro da rede interna', 'Uma rede Wi-Fi para visitantes'],
    answer: 1,
    explanation: 'Uma DMZ é uma rede de perímetro que isola servidores acessíveis publicamente (como servidores web e de e-mail) do resto da rede interna, adicionando uma camada de segurança.',
  },
  {
    id: 88,
    topicId: 'seguranca-de-rede',
    question: 'Qual é a diferença entre um IDS e um IPS?',
    options: ['IDS é para redes internas, IPS para externas', 'IDS detecta ataques, enquanto IPS tenta bloqueá-los ativamente', 'IPS detecta ataques, enquanto IDS tenta bloqueá-los', 'Não há diferença'],
    answer: 1,
    explanation: 'Um IDS (Intrusion Detection System) é passivo e apenas alerta sobre possíveis ameaças. Um IPS (Intrusion Prevention System) é ativo e pode tomar medidas para impedir que o ataque seja bem-sucedido.',
  },
  {
    id: 89,
    topicId: 'seguranca-de-rede',
    question: 'Qual política de firewall é considerada a mais segura?',
    options: ['Permitir tudo por padrão e negar exceções', 'Negar tudo por padrão e permitir exceções (negação implícita)', 'Permitir todo tráfego de saída', 'Bloquear apenas a porta 80'],
    answer: 1,
    explanation: 'A política de "negação implícita" é a mais segura. Por padrão, nada é permitido, e apenas o tráfego explicitamente necessário para as operações é liberado através de regras específicas.',
  },
  {
    id: 90,
    topicId: 'seguranca-de-rede',
    question: 'O que é um ataque "Man-in-the-Middle" (MitM)?',
    options: ['Um vírus que se espalha por e-mail', 'Um atacante que intercepta e possivelmente altera a comunicação entre duas partes', 'Um ataque que adivinha senhas', 'Um tipo de ransomware'],
    answer: 1,
    explanation: 'Em um ataque MitM, o invasor se posiciona secretamente entre duas partes que acreditam estar se comunicando diretamente, permitindo que ele leia e modifique o tráfego.',
  },
  {
    id: 91,
    topicId: 'seguranca-de-rede',
    question: 'O que o hashing (ex: SHA-256) garante?',
    options: ['Confidencialidade', 'Disponibilidade', 'Autenticação', 'Integridade'],
    answer: 3,
    explanation: 'Funções de hash criam uma "impressão digital" de tamanho fixo para um bloco de dados. Se os dados forem alterados, o hash resultante será diferente, o que permite verificar se os dados mantiveram sua integridade.',
  },
  {
    id: 92,
    topicId: 'seguranca-de-rede',
    question: 'Usar uma senha e um código de uso único gerado em seu smartphone é um exemplo de:',
    options: ['Autenticação de Fator Único', 'Autenticação de Dois Fatores (2FA)', 'Criptografia Simétrica', 'Biometria'],
    answer: 1,
    explanation: '2FA combina dois tipos diferentes de prova: algo que você sabe (senha) e algo que você tem (seu smartphone). Isso torna o acesso muito mais seguro.',
  },
  {
    id: 93,
    topicId: 'seguranca-de-rede',
    question: 'O que é um "honeypot"?',
    options: ['Uma senha mestra para a rede', 'Um sistema de chamariz para atrair e estudar atacantes', 'Um tipo de firewall avançado', 'Um software de backup seguro'],
    answer: 1,
    explanation: 'Um honeypot é um sistema sacrificial projetado para parecer valioso e vulnerável, com o objetivo de atrair atacantes para que suas táticas possam ser estudadas e eles sejam desviados dos sistemas reais.',
  },
  {
    id: 94,
    topicId: 'seguranca-de-rede',
    question: 'O que significa "hardening" de um sistema?',
    options: ['Aumentar sua capacidade de processamento', 'Torná-lo fisicamente mais resistente', 'Reduzir sua superfície de ataque, desativando serviços e portas desnecessários', 'Instalar mais memória RAM'],
    answer: 2,
    explanation: 'Hardening é o processo de proteger um sistema, tornando-o mais seguro. Isso envolve remover softwares desnecessários, aplicar patches, configurar permissões e fechar portas que não estão em uso.',
  },
  {
    id: 95,
    topicId: 'seguranca-de-rede',
    question: 'Qual tipo de malware se anexa a um programa legítimo e se espalha quando esse programa é executado?',
    options: ['Worm', 'Vírus', 'Spyware', 'Adware'],
    answer: 1,
    explanation: 'Um vírus de computador precisa de um programa hospedeiro. Ele se insere em um arquivo executável e, quando o usuário roda esse arquivo, o vírus é ativado e tenta infectar outros programas.',
  },
  {
    id: 96,
    topicId: 'seguranca-de-rede',
    question: 'A filtragem de endereços MAC em uma rede Wi-Fi é uma medida de segurança forte?',
    options: ['Sim, é à prova de falhas.', 'Não, porque endereços MAC podem ser facilmente falsificados (spoofed).', 'Sim, porque endereços MAC são criptografados.', 'Não, porque é muito caro de implementar.'],
    answer: 1,
    explanation: 'Embora possa impedir usuários casuais, a filtragem de MAC é considerada uma segurança fraca, pois um atacante pode facilmente monitorar a rede, descobrir os MACs permitidos e falsificar o seu próprio.',
  },
  {
    id: 97,
    topicId: 'seguranca-de-rede',
    question: 'O que é uma vulnerabilidade de "dia zero" (zero-day)?',
    options: ['Uma vulnerabilidade que é explorada no primeiro dia do mês.', 'Uma falha de segurança que é desconhecida pelo fornecedor e para a qual não existe correção.', 'Uma vulnerabilidade que só afeta sistemas por um dia.', 'Uma falha que permite acesso total ao sistema.'],
    answer: 1,
    explanation: 'Um ataque de "dia zero" explora uma vulnerabilidade que acaba de ser descoberta e para a qual o fornecedor do software ainda não teve tempo de criar um patch, deixando os usuários indefesos.',
  },
  {
    id: 98,
    topicId: 'seguranca-de-rede',
    question: 'Qual o objetivo do padrão IEEE 802.1X?',
    options: ['Aumentar a velocidade do Wi-Fi.', 'Fornecer autenticação de dispositivos na rede antes de conceder o acesso.', 'Padronizar cabos de rede.', 'Criptografar todo o tráfego da Internet.'],
    answer: 1,
    explanation: '802.1X é um padrão de controle de acesso à rede baseado em portas. Ele exige que os dispositivos se autentiquem (geralmente contra um servidor RADIUS) antes de poderem acessar os recursos da LAN ou WLAN.',
  },
  {
    id: 99,
    topicId: 'seguranca-de-rede',
    question: 'Qual tipo de malware se propaga automaticamente por redes, sem precisar de um programa hospedeiro?',
    options: ['Vírus', 'Cavalo de Troia (Trojan)', 'Worm', 'Rootkit'],
    answer: 2,
    explanation: 'Diferente de um vírus, um worm é um malware autônomo que pode se replicar e se espalhar por uma rede por conta própria, explorando vulnerabilidades para infectar outros sistemas.',
  },
  {
    id: 100,
    topicId: 'seguranca-de-rede',
    question: 'Criptografia assimétrica usa:',
    options: ['Uma única chave secreta', 'Duas chaves: uma pública e uma privada', 'Nenhuma chave', 'Uma chave que muda a cada sessão'],
    answer: 1,
    explanation: 'Na criptografia assimétrica, uma chave pública é usada para criptografar os dados, e apenas a chave privada correspondente pode descriptografá-los, o que permite a comunicação segura sem o compartilhamento prévio de um segredo.',
  },
  {
    id: 101,
    topicId: 'modelos-osi-tcpip',
    question: 'Qual é a unidade de Dados de Protocolo, ou PDU (Protocol Data Unit), da camada de aplicação?',
    options: ['Quadro', 'Célula', 'Mensagem', 'Segmento', 'Pacote'],
    answer: 2,
    explanation: 'Na camada de aplicação, a PDU é geralmente chamada de Mensagem. As outras opções correspondem a outras camadas: Quadro (Enlace), Segmento (Transporte) e Pacote (Rede).',
  },
  {
    id: 102,
    topicId: 'modelos-osi-tcpip',
    question: 'Um sistema de comunicação é um conjunto de entidades (ou partes) coordenadas, que concorrem para a transferência de dados. Ocorre entre duas partes, sendo que em uma há um emissor e na outra um receptor. A tarefa de cada camada de comunicação é adicionar um cabeçalho ou um trailer para um envelope de dados. Este processo é conhecido como:',
    options: ['Unidade de processamento', 'Unidade de receptores', 'Fluxo de Dados', 'Encapsulamento', 'Elementos desconexos'],
    answer: 3,
    explanation: 'Encapsulamento é o processo de adicionar informações de controle (cabeçalhos e trailers) aos dados à medida que eles passam pelas camadas do modelo de rede.',
  },
  {
    id: 103,
    topicId: 'protocolos-essenciais',
    question: 'A camada de transporte, padrão geralmente da camada de aplicação entre os lados do cliente e servidor de uma aplicação na Internet, lida com a conexão na Internet. TCP e UDP são os dois principais protocolos da camada de transporte. Quais serviços o TCP oferece?',
    options: ['Transferência de dados confiável, Controle de fluxo', 'Transferência de dados confiável, Controle de fluxo, Correção de erros', 'Controle de fluxo', 'Transferência de dados confiável'],
    answer: 1,
    explanation: 'O TCP fornece transferência de dados confiável (garantindo que os dados cheguem em ordem e sem perdas), controle de fluxo (para não sobrecarregar o receptor) e correção de erros.',
  },
  {
    id: 104,
    topicId: 'protocolos-essenciais',
    question: 'O conteúdo sistema_edu, .gov, .com, .mil, .org, .net e .int para nomear sites é mais fácil de lembrar do que a sintaxe de números 192.168.1.5 para um computador. O protocolo da camada de aplicação que permite que os usuários se conectem a sites de pesquisa por meio de nomes em vez de números, por exemplo, é:',
    options: ['FTP', 'HTTP', 'Telnet', 'DNS', 'SSH'],
    answer: 3,
    explanation: 'O DNS (Domain Name System) é o protocolo responsável por traduzir nomes de domínio legíveis por humanos (como www.exemplo.com) em endereços IP numéricos que os computadores usam.',
  },
  {
    id: 105,
    topicId: 'conceitos-basicos',
    question: 'A transmissão de sinais através de um cabo de par trançado significa que o cabo leva a informação, ou energia eletromagnética, adiante. A interferência que sai de uma ligação em sua casa e as ondas de rádio são o tipo de energia que causa um ruído na linha do telefone. O ruído do ambiente externo pode perturbar o sinal. Marque a alternativa que oferece a solução de menor custo:',
    options: ['Fibra ótica', 'Cabo coaxial', 'Cabo de par trançado', 'Sem custo', 'Micro-ondas'],
    answer: 2,
    explanation: 'O cabo de par trançado é a solução de cabeamento mais econômica para redes locais e oferece boa proteção contra interferências de baixo nível, tornando-o a opção de menor custo entre as alternativas viáveis.',
  },
  {
    id: 106,
    topicId: 'modelos-osi-tcpip',
    question: 'De sete camadas do modelo de referência OSI são: de aplicação, de apresentação, de sessão, de transporte, de rede, de enlace e de física. O protocolo de rede trabalha com os endereços de origem e destino, e ele tem a seguinte função: "Determinar o roteamento da mensagem entre a origem até o destino". A qual camada corresponde essa função?',
    options: ['Física', 'Transporte', 'Rede', 'Aplicação', 'Sessão'],
    answer: 2,
    explanation: 'A camada de Rede (Camada 3) é responsável pelo endereçamento lógico e pelo roteamento, determinando o melhor caminho para os pacotes viajarem através de múltiplas redes.',
  },
  {
    id: 107,
    topicId: 'modelos-osi-tcpip',
    question: 'Em cada camada, uma Unidade de Dados de Protocolo, ou PDU (Protocol Data Unit), possui campos de cabeçalho. Em qual camada e protocolo o PDU (Protocol Data Unit) possui um cabeçalho chamado "pacote"?',
    options: ['Quadro', 'Mensagem', 'Segmento', 'Datagrama', 'Pacote'],
    answer: 4,
    explanation: 'A PDU da camada de Rede (Camada 3) é chamada de Pacote (Packet).',
  },
  {
    id: 108,
    topicId: 'modelos-osi-tcpip',
    question: 'Em cada camada, uma Unidade de Dados de Protocolo, ou PDU (Protocol Data Unit), possui campos de cabeçalho. Em qual camada e protocolo o PDU possui um cabeçalho chamado "datagrama"?',
    options: ['Quadro', 'Célula', 'Mensagem', 'Pacote', 'Segmento'],
    answer: 3,
    explanation: 'O termo Datagrama é mais comumente associado à PDU da camada de Transporte quando se usa o protocolo UDP. Também pode se referir à PDU da camada de Rede (IP). Dado o contexto das opções, Pacote é a resposta mais precisa para a camada de Rede.',
  },
  {
    id: 109,
    topicId: 'protocolos-essenciais',
    question: 'A camada de transporte carrega mensagens da camada de aplicação entre os lados do cliente e servidor de uma aplicação na Internet. TCP é um dos dois principais protocolos da camada de transporte. Quais são os serviços corretos que o TCP oferece? I. Transferência de dados confiável. II. Controle de fluxo. III. Correção de erros.',
    options: ['I, II.', 'I, II, III.', 'II.', 'I.', 'II, I.'],
    answer: 1,
    explanation: 'TCP é um protocolo orientado à conexão que fornece transferência de dados confiável, controle de fluxo e verificação de erros para garantir a integridade e a ordem dos dados.',
  },
  {
    id: 110,
    topicId: 'modelos-osi-tcpip',
    question: 'São as atividades ou funções que envolvem um pacote quando ele chega ao seu destino, por exemplo, o encapsulamento, o fluxo de dados, o endereçamento, etc. Quando o pacote é transmitido para um ou mais destinos, as atividades ou funções envolvidas incluem o encapsulamento. A transmissão de um pacote de dados para um ou mais destinos é um processo que envolve a criação de um pacote de dados, a seleção de um ou mais destinos, a transmissão do pacote e a confirmação de recebimento do pacote. Qual é o nome das ações realizadas na transmissão e/ou no recebimento de uma mensagem que inclui um pacote?',
    options: ['Encapsulamento', 'Serviços', 'Fluxo', 'Protocolo', 'Link'],
    answer: 0,
    explanation: 'Encapsulamento é o processo fundamental de adicionar cabeçalhos e trailers de controle aos dados à medida que eles descem pelas camadas de protocolo para transmissão.',
  }
];


export const weeklyProgress = [
  { week: 'Semana 1', points: 150 },
  { week: 'Semana 2', points: 220 },
  { week: 'Semana 3', points: 180 },
  { week: 'Semana 4', points: 350 },
];
