import type { ComponentType } from 'react';
import { OsiTcpIpIcon, SubnettingIcon, NetworkProtocolsIcon, NetworkDevicesIcon, NetworkSecurityIcon } from './icons.tsx';

export interface Topic {
  id: string;
  name: string;
  description: string;
  icon: ComponentType<{ className?: string }>;
}

export const topics: Topic[] = [
  {
    id: 'osi-tcp-ip',
    name: 'Modelos OSI/TCP-IP',
    description: 'Entenda os modelos fundamentais da comunicação de rede.',
    icon: OsiTcpIpIcon,
  },
  {
    id: 'subnetting',
    name: 'Sub-redes e Endereçamento IP',
    description: 'Domine o endereçamento IPv4/IPv6 e a segmentação de rede.',
    icon: SubnettingIcon,
  },
  {
    id: 'protocols',
    name: 'Protocolos de Rede',
    description: 'Aprenda sobre TCP, UDP, HTTP, DNS e outros protocolos essenciais.',
    icon: NetworkProtocolsIcon,
  },
  {
    id: 'devices',
    name: 'Dispositivos de Rede',
    description: 'Explore switches, roteadores, firewalls e suas funções.',
    icon: NetworkDevicesIcon,
  },
  {
    id: 'security',
    name: 'Segurança de Rede',
    description: 'Mergulhe nos princípios de segurança da infraestrutura de rede.',
    icon: NetworkSecurityIcon,
  },
];

export interface Question {
  id: number;
  topicId: string;
  question: string;
  options: string[];
  answer: number;
  explanation: string;
}

export interface ClientTopic {
  id: string;
  name: string;
  description: string;
}

export function getIconForTopic(topicId: string): ComponentType<{ className?: string }> {
  const topic = topics.find(t => t.id === topicId);
  return topic ? topic.icon : () => null;
}

export const questions: Question[] = [
  // OSI/TCP-IP - 20 questions
  {
    id: 1,
    topicId: 'osi-tcp-ip',
    question: 'Qual camada do modelo OSI é responsável pelo roteamento e encaminhamento de pacotes IP?',
    options: ['Camada Física', 'Camada de Enlace de Dados', 'Camada de Rede', 'Camada de Transporte'],
    answer: 2,
    explanation: 'A Camada de Rede (Camada 3) é responsável pelo endereçamento lógico, roteamento e determinação de caminho. Ela move pacotes entre hosts em redes diferentes.',
  },
  {
    id: 2,
    topicId: 'osi-tcp-ip',
    question: 'Em qual camada do modelo TCP/IP o protocolo TCP opera?',
    options: ['Aplicação', 'Transporte', 'Internet', 'Acesso à Rede'],
    answer: 1,
    explanation: 'O TCP (Protocolo de Controle de Transmissão) é um protocolo orientado à conexão que opera na Camada de Transporte, fornecendo entrega confiável, ordenada и com verificação de erros.',
  },
  {
    id: 3,
    topicId: 'osi-tcp-ip',
    question: 'A camada de Enlace de Dados é responsável por quê?',
    options: ['Detecção e correção de erros', 'Enquadramento e endereçamento MAC', 'Roteamento', 'Geração de sinal'],
    answer: 1,
    explanation: 'A camada de Enlace de Dados (Camada 2) é responsável pela transferência de dados de nó a nó e lida com enquadramento, endereçamento físico (MAC) e detecção de erros.',
  },
  {
    id: 12,
    topicId: 'osi-tcp-ip',
    question: 'Qual camada do modelo OSI lida com a formatação e criptografia de dados?',
    options: ['Camada de Apresentação', 'Camada de Sessão', 'Camada de Aplicação', 'Camada de Transporte'],
    answer: 0,
    explanation: 'A Camada de Apresentação (Camada 6) garante que os dados sejam apresentados em um formato que o dispositivo receptor possa entender, lidando com tradução, criptografia e compressão.',
  },
  {
    id: 13,
    topicId: 'osi-tcp-ip',
    question: 'O protocolo HTTP opera em qual camada do modelo OSI?',
    options: ['Camada de Sessão', 'Camada de Rede', 'Camada de Transporte', 'Camada de Aplicação'],
    answer: 3,
    explanation: 'O HTTP (Protocolo de Transferência de Hipertexto) é um protocolo da Camada de Aplicação (Camada 7) usado para a comunicação na World Wide Web.',
  },
  {
    id: 14,
    topicId: 'osi-tcp-ip',
    question: 'Qual das seguintes opções é uma função da Camada Física do modelo OSI?',
    options: ['Controle de fluxo', 'Endereçamento de quadros', 'Especificações elétricas e mecânicas', 'Roteamento de pacotes'],
    answer: 2,
    explanation: 'A Camada Física (Camada 1) define as especificações elétricas, mecânicas e de procedimento para o meio físico, incluindo cabos, conectores e sinalização.',
  },
  {
    id: 15,
    topicId: 'osi-tcp-ip',
    question: 'A Camada de Transporte do modelo OSI fornece qual tipo de serviço?',
    options: ['Comunicação de processo a processo', 'Roteamento entre redes', 'Formatação de dados', 'Controle de acesso ao meio'],
    answer: 0,
    explanation: 'A Camada de Transporte (Camada 4) fornece serviços de comunicação de processo a processo, como TCP (confiável) e UDP (não confiável).',
  },
  {
    id: 16,
    topicId: 'osi-tcp-ip',
    question: 'Qual camada do modelo TCP/IP corresponde às camadas de Sessão, Apresentação e Aplicação do modelo OSI?',
    options: ['Transporte', 'Aplicação', 'Internet', 'Acesso à Rede'],
    answer: 1,
    explanation: 'A camada de Aplicação do modelo TCP/IP engloba as funcionalidades das camadas de Aplicação, Apresentação e Sessão do modelo OSI.',
  },
  {
    id: 17,
    topicId: 'osi-tcp-ip',
    question: 'O endereço MAC (Media Access Control) é usado em qual camada do modelo OSI?',
    options: ['Camada de Rede', 'Camada Física', 'Camada de Enlace de Dados', 'Camada de Transporte'],
    answer: 2,
    explanation: 'O endereço MAC é um endereço físico usado na Camada de Enlace de Dados (Camada 2) para identificar dispositivos em uma rede local.',
  },
  {
    id: 18,
    topicId: 'osi-tcp-ip',
    question: 'Qual PDU (Protocol Data Unit) é usada na Camada de Rede?',
    options: ['Quadro (Frame)', 'Segmento (Segment)', 'Pacote (Packet)', 'Bit'],
    answer: 2,
    explanation: 'A PDU da Camada de Rede é o pacote. A Camada de Enlace usa quadros, a Camada de Transporte usa segmentos (TCP) ou datagramas (UDP), e a Camada Física lida com bits.',
  },
  {
    id: 19,
    topicId: 'osi-tcp-ip',
    question: 'A função de "controle de diálogo" pertence a qual camada OSI?',
    options: ['Camada de Sessão', 'Camada de Apresentação', 'Camada de Transporte', 'Camada de Aplicação'],
    answer: 0,
    explanation: 'A Camada de Sessão (Camada 5) é responsável por estabelecer, gerenciar e encerrar sessões, incluindo o controle de diálogo (quem transmite, quando, por quanto tempo).',
  },
  {
    id: 20,
    topicId: 'osi-tcp-ip',
    question: 'O modelo TCP/IP tem quantas camadas?',
    options: ['7', '5', '4', '3'],
    answer: 2,
    explanation: 'O modelo TCP/IP é comumente descrito como tendo 4 camadas: Acesso à Rede, Internet, Transporte e Aplicação.',
  },
  {
    id: 21,
    topicId: 'osi-tcp-ip',
    question: 'Qual das opções a seguir NÃO é uma camada do modelo OSI?',
    options: ['Camada de Internet', 'Camada de Sessão', 'Camada de Rede', 'Camada Física'],
    answer: 0,
    explanation: 'A "Camada de Internet" pertence ao modelo TCP/IP, não ao modelo OSI. O modelo OSI possui uma "Camada de Rede" em seu lugar.',
  },
  {
    id: 22,
    topicId: 'osi-tcp-ip',
    question: 'O UDP (User Datagram Protocol) é um protocolo...',
    options: ['Confiável e orientado à conexão', 'Não confiável e não orientado à conexão', 'Confiável e não orientado à conexão', 'Não confiável e orientado à conexão'],
    answer: 1,
    explanation: 'UDP é um protocolo não confiável e não orientado à conexão que opera na Camada de Transporte. Ele não garante entrega, ordem ou verificação de erros, tornando-o rápido mas menos robusto que o TCP.',
  },
  {
    id: 23,
    topicId: 'osi-tcp-ip',
    question: 'Qual camada OSI é responsável pela sincronização de pontos de verificação?',
    options: ['Transporte', 'Rede', 'Apresentação', 'Sessão'],
    answer: 3,
    explanation: 'A camada de Sessão (Camada 5) gerencia o diálogo entre computadores. Ela pode criar pontos de verificação em uma sequência de dados, de modo que, se a transmissão falhar, apenas os dados após o último ponto de verificação precisam ser retransmitidos.',
  },
  {
    id: 24,
    topicId: 'osi-tcp-ip',
    question: 'O que é encapsulamento no contexto de redes?',
    options: ['O processo de criptografar dados', 'O processo de adicionar cabeçalhos a dados à medida que eles descem as camadas do modelo', 'O processo de remover cabeçalhos de dados à medida que eles sobem as camadas', 'O processo de comprimir dados para transmissão'],
    answer: 1,
    explanation: 'Encapsulamento é o processo no qual informações de controle (cabeçalhos) são adicionadas aos dados em cada camada do modelo de rede, preparando-os para transmissão.',
  },
  {
    id: 25,
    topicId: 'osi-tcp-ip',
    question: 'Qual camada do modelo TCP/IP é responsável por encontrar a melhor rota para um pacote?',
    options: ['Acesso à Rede', 'Transporte', 'Internet', 'Aplicação'],
    answer: 2,
    explanation: 'A camada de Internet do modelo TCP/IP (equivalente à camada de Rede do OSI) é responsável pelo endereçamento, empacotamento e roteamento de pacotes.',
  },
  {
    id: 26,
    topicId: 'osi-tcp-ip',
    question: 'A PDU da camada de Enlace de Dados é chamada de:',
    options: ['Pacote', 'Segmento', 'Bit', 'Quadro'],
    answer: 3,
    explanation: 'A Unidade de Dados de Protocolo (PDU) na camada de Enlace de Dados (Camada 2) é chamada de Quadro (Frame).',
  },
  {
    id: 27,
    topicId: 'osi-tcp-ip',
    question: 'Qual camada OSI lida com a tradução de sintaxe entre sistemas diferentes?',
    options: ['Aplicação', 'Apresentação', 'Sessão', 'Transporte'],
    answer: 1,
    explanation: 'A camada de Apresentação (Camada 6) é responsável por traduzir dados entre o formato de rede e o formato esperado pela aplicação, garantindo que sistemas diferentes possam se comunicar.',
  },
  {
    id: 28,
    topicId: 'osi-tcp-ip',
    question: 'Qual protocolo é usado para resolver um endereço IP para um endereço MAC?',
    options: ['DHCP', 'DNS', 'ARP', 'RARP'],
    answer: 2,
    explanation: 'O ARP (Address Resolution Protocol) é usado para descobrir o endereço da camada de enlace (endereço MAC) associado a um determinado endereço da camada de internet (endereço IP).',
  },
  // Subnetting - 20 questions
  {
    id: 4,
    topicId: 'subnetting',
    question: 'Qual é a máscara de sub-rede para uma rede /27?',
    options: ['255.255.255.0', '255.255.255.192', '255.255.255.224', '255.255.255.240'],
    answer: 2,
    explanation: 'Um prefixo /27 significa que 27 bits são usados para a porção de rede. A máscara de sub-rede é 11111111.11111111.11111111.11100000, que se traduz em 255.255.255.224.',
  },
  {
    id: 5,
    topicId: 'subnetting',
    question: 'Quantos endereços de host utilizáveis existem em uma sub-rede /29?',
    options: ['6', '8', '14', '30'],
    answer: 0,
    explanation: 'Um prefixo /29 deixa 32 - 29 = 3 bits para hosts. Isso dá 2^3 = 8 endereços totais. Subtraindo o endereço de rede e o endereço de broadcast, restam 6 endereços de host utilizáveis.',
  },
  {
    id: 29,
    topicId: 'subnetting',
    question: 'Qual é o endereço de broadcast da rede 192.168.10.64/26?',
    options: ['192.168.10.127', '192.168.10.255', '192.168.10.95', '192.168.10.128'],
    answer: 0,
    explanation: 'Uma rede /26 tem 64 endereços. Começando em .64, o intervalo vai de 192.168.10.64 a 192.168.10.127. O último endereço no intervalo é sempre o endereço de broadcast.',
  },
  {
    id: 30,
    topicId: 'subnetting',
    question: 'Qual das seguintes opções é um endereço IP privado?',
    options: ['172.15.25.62', '172.20.14.36', '192.169.2.5', '11.0.0.1'],
    answer: 1,
    explanation: 'Os intervalos de IP privado são 10.0.0.0/8, 172.16.0.0/12 e 192.168.0.0/16. O endereço 172.20.14.36 se encaixa no intervalo de 172.16.0.0 a 172.31.255.255.',
  },
  {
    id: 31,
    topicId: 'subnetting',
    question: 'Você precisa criar 5 sub-redes a partir do bloco 192.168.1.0/24. Qual máscara de sub-rede você usaria?',
    options: ['/25', '/26', '/27', '/28'],
    answer: 2,
    explanation: 'Para obter 5 sub-redes, você precisa de 3 bits (2^3 = 8 sub-redes). Adicionar 3 bits ao prefixo original /24 resulta em um novo prefixo de /27.',
  },
  {
    id: 32,
    topicId: 'subnetting',
    question: 'Qual é o endereço de rede para o host 10.10.10.75 com a máscara 255.255.255.240?',
    options: ['10.10.10.0', '10.10.10.64', '10.10.10.72', '10.10.10.80'],
    answer: 1,
    explanation: 'A máscara 255.255.255.240 (/28) cria sub-redes com 16 endereços. Os múltiplos são 0, 16, 32, 48, 64, 80... O endereço 75 está no intervalo 64-79, então o endereço de rede é 10.10.10.64.',
  },
  {
    id: 33,
    topicId: 'subnetting',
    question: 'Quantos bits estão na porção de host de um endereço com máscara /22?',
    options: ['8', '10', '12', '22'],
    answer: 1,
    explanation: 'Um endereço IPv4 tem 32 bits. Se 22 bits são para a rede, então 32 - 22 = 10 bits restam para a porção de host.',
  },
  {
    id: 34,
    topicId: 'subnetting',
    question: 'Qual é o primeiro endereço de host utilizável na rede 172.16.32.0/20?',
    options: ['172.16.32.0', '172.16.32.1', '172.16.0.1', '172.16.31.255'],
    answer: 1,
    explanation: 'O endereço de rede é 172.16.32.0. O primeiro endereço de host utilizável é sempre o endereço de rede mais um.',
  },
  {
    id: 35,
    topicId: 'subnetting',
    question: 'O endereço 2001:0db8:85a3:0000:0000:8a2e:0370:7334 é um exemplo de qual tipo de endereço?',
    options: ['IPv4', 'MAC', 'IPv6', 'APIPA'],
    answer: 2,
    explanation: 'Este é um endereço IPv6, caracterizado por oito grupos de quatro dígitos hexadecimais, separados por dois pontos.',
  },
  {
    id: 36,
    topicId: 'subnetting',
    question: 'Qual é a notação CIDR para a máscara de sub-rede 255.255.255.192?',
    options: ['/24', '/25', '/26', '/27'],
    answer: 2,
    explanation: 'A máscara 255.255.255.192 tem 26 bits definidos como 1 (8+8+8+2), portanto, sua notação CIDR é /26.',
  },
  {
    id: 37,
    topicId: 'subnetting',
    question: 'Uma rede Classe C por padrão usa qual máscara de sub-rede?',
    options: ['255.0.0.0', '255.255.0.0', '255.255.255.0', '255.255.255.255'],
    answer: 2,
    explanation: 'O endereçamento classful (obsoleto, mas ainda referenciado) designa 255.255.255.0 (/24) como a máscara padrão para redes Classe C.',
  },
  {
    id: 38,
    topicId: 'subnetting',
    question: 'O que é APIPA (Automatic Private IP Addressing)?',
    options: ['Um protocolo para atribuir endereços IP públicos', 'Um endereço IPv6 especial', 'Um endereço no intervalo 169.254.0.0/16 que um host se atribui quando não consegue encontrar um servidor DHCP', 'Um método de encapsulamento'],
    answer: 2,
    explanation: 'APIPA é um recurso do Windows que atribui automaticamente um endereço IP do intervalo 169.254.0.1 a 169.254.255.254 se um servidor DHCP não estiver disponível.',
  },
  {
    id: 39,
    topicId: 'subnetting',
    question: 'Em IPv6, o que ::1 representa?',
    options: ['Um endereço não especificado', 'O endereço de loopback', 'Um endereço de broadcast', 'O primeiro endereço em uma sub-rede'],
    answer: 1,
    explanation: '::1 é o endereço de loopback em IPv6, equivalente a 127.0.0.1 em IPv4. Ele é usado por um host para enviar pacotes para si mesmo.',
  },
  {
    id: 40,
    topicId: 'subnetting',
    question: 'Quantos endereços de host utilizáveis uma máscara /23 fornece?',
    options: ['254', '510', '512', '1022'],
    answer: 1,
    explanation: 'Um prefixo /23 deixa 32 - 23 = 9 bits para hosts. 2^9 = 512. Subtraindo o endereço de rede e o de broadcast, restam 510 endereços utilizáveis.',
  },
  {
    id: 41,
    topicId: 'subnetting',
    question: 'O que é VLSM (Variable Length Subnet Mask)?',
    options: ['Uma máscara de sub-rede fixa para toda a rede', 'O uso de diferentes máscaras de sub-rede para diferentes sub-redes da mesma rede', 'Um tipo de endereço IPv6', 'Um protocolo de roteamento'],
    answer: 1,
    explanation: 'VLSM permite o uso de diferentes máscaras de sub-rede para diferentes sub-redes, o que otimiza o uso de endereços IP.',
  },
  {
    id: 42,
    topicId: 'subnetting',
    question: 'Qual é o endereço IPv4 de loopback?',
    options: ['192.168.0.1', '10.0.0.1', '127.0.0.1', '169.254.1.1'],
    answer: 2,
    explanation: '127.0.0.1 é o endereço de loopback padrão para IPv4, usado para testar a pilha de rede localmente em um host.',
  },
  {
    id: 43,
    topicId: 'subnetting',
    question: 'O endereço 224.0.0.5 é um exemplo de que tipo de endereço?',
    options: ['Unicast', 'Broadcast', 'Multicast', 'Anycast'],
    answer: 2,
    explanation: 'O intervalo 224.0.0.0 a 239.255.255.255 é reservado para endereços multicast. 224.0.0.5 é usado pelo protocolo OSPF.',
  },
  {
    id: 44,
    topicId: 'subnetting',
    question: 'Como você pode abreviar o endereço IPv6 fe80:0000:0000:0000:0202:b3ff:fe1e:8329?',
    options: ['fe80::202:b3ff:fe1e:8329', 'fe80:0:0:0:202:b3ff:fe1e:8329', 'fe80::0202:b3ff:fe1e:8329', 'fe80:0000::b3ff:fe1e:8329'],
    answer: 0,
    explanation: 'Em IPv6, sequências de zeros podem ser substituídas por "::" uma vez, e zeros à esquerda em cada bloco podem ser omitidos. A abreviação correta é fe80::202:b3ff:fe1e:8329.',
  },
  {
    id: 45,
    topicId: 'subnetting',
    question: 'Uma empresa precisa de 25 endereços de host para uma sub-rede. Qual é o menor prefixo de sub-rede (CIDR) que atenderia a essa necessidade?',
    options: ['/28', '/27', '/26', '/25'],
    answer: 1,
    explanation: 'Para 25 hosts, precisamos de pelo menos 5 bits de host (2^5 = 32 endereços). 32 - 5 = 27. Um prefixo /27 fornece 30 hosts utilizáveis, o que é suficiente.',
  },
  {
    id: 46,
    topicId: 'subnetting',
    question: 'Qual é a principal razão para usar sub-redes?',
    options: ['Para aumentar a velocidade da internet', 'Para dividir uma rede grande em redes menores e mais gerenciáveis', 'Para simplificar os endereços IP', 'Para eliminar a necessidade de roteadores'],
    answer: 1,
    explanation: 'A criação de sub-redes ajuda a reduzir o tráfego de broadcast, melhorar a segurança e o desempenho da rede, e simplificar o gerenciamento, dividindo um grande domínio de broadcast em vários menores.',
  },
  // Protocols - 20 questions
  {
    id: 6,
    topicId: 'protocols',
    question: 'Qual protocolo não tem estado (stateless)?',
    options: ['TCP', 'HTTP', 'FTP', 'Telnet'],
    answer: 1,
    explanation: 'O HTTP é um protocolo sem estado, o que significa que cada solicitação de um cliente para um servidor é tratada como uma transação independente. O servidor não retém nenhuma informação de sessão sobre o cliente.',
  },
  {
    id: 7,
    topicId: 'protocols',
    question: 'Qual porta o DNS usa principalmente?',
    options: ['25', '53', '80', '443'],
    answer: 1,
    explanation: 'O Sistema de Nomes de Domínio (DNS) usa principalmente a porta UDP 53 para consultas. Ele também pode usar a porta TCP 53 para transferências de zona.',
  },
  {
    id: 47,
    topicId: 'protocols',
    question: 'Qual protocolo da camada de transporte fornece entrega garantida e ordenada de pacotes?',
    options: ['UDP', 'TCP', 'IP', 'ICMP'],
    answer: 1,
    explanation: 'O TCP (Transmission Control Protocol) é orientado à conexão e fornece entrega confiável, ordenada e com verificação de erros através do uso de handshakes e números de sequência.',
  },
  {
    id: 48,
    topicId: 'protocols',
    question: 'O que o DHCP (Dynamic Host Configuration Protocol) faz?',
    options: ['Resolve nomes de domínio para endereços IP', 'Atribui endereços IP dinamicamente aos hosts', 'Transfere arquivos entre hosts', 'Fornece acesso seguro a terminais remotos'],
    answer: 1,
    explanation: 'O DHCP automatiza o processo de configuração de hosts em uma rede, atribuindo-lhes endereços IP, máscaras de sub-rede, gateways padrão e servidores DNS.',
  },
  {
    id: 49,
    topicId: 'protocols',
    question: 'Qual protocolo é usado para enviar e-mails?',
    options: ['POP3', 'IMAP', 'SMTP', 'HTTP'],
    answer: 2,
    explanation: 'O SMTP (Simple Mail Transfer Protocol) é o protocolo padrão para enviar (ou "empurrar") e-mails de um cliente para um servidor e entre servidores de e-mail.',
  },
  {
    id: 50,
    topicId: 'protocols',
    question: 'O comando "ping" usa qual protocolo para testar a conectividade?',
    options: ['TCP', 'UDP', 'ICMP', 'ARP'],
    answer: 2,
    explanation: 'O utilitário ping usa o ICMP (Internet Control Message Protocol), enviando uma "solicitação de eco" e aguardando uma "resposta de eco" para determinar a conectividade e a latência.',
  },
  {
    id: 51,
    topicId: 'protocols',
    question: 'Qual porta o HTTPS usa por padrão?',
    options: ['80', '21', '22', '443'],
    answer: 3,
    explanation: 'O HTTPS (HTTP Secure) usa a porta 443 para estabelecer uma comunicação segura e criptografada entre o cliente e o servidor.',
  },
  {
    id: 52,
    topicId: 'protocols',
    question: 'FTP (File Transfer Protocol) usa quais portas?',
    options: ['Porta 25 para controle e dados', 'Porta 80 para controle e 81 para dados', 'Porta 21 para controle e uma porta dinâmica para dados', 'Porta 22 para controle e dados'],
    answer: 2,
    explanation: 'O FTP usa a porta 21 para o canal de controle (comandos) e, no modo ativo, a porta 20 para o canal de dados. No modo passivo, ele usa uma porta dinâmica para dados.',
  },
  {
    id: 53,
    topicId: 'protocols',
    question: 'Qual é a principal vantagem do UDP sobre o TCP?',
    options: ['Confiabilidade', 'Ordenação de pacotes', 'Baixa sobrecarga (overhead)', 'Controle de fluxo'],
    answer: 2,
    explanation: 'O UDP tem uma sobrecarga muito menor que o TCP porque não estabelece conexão e não possui mecanismos de confirmação ou retransmissão, tornando-o mais rápido para aplicações sensíveis ao tempo como streaming e jogos online.',
  },
  {
    id: 54,
    topicId: 'protocols',
    question: 'O RDP (Remote Desktop Protocol) opera em qual porta?',
    options: ['22', '23', '3389', '8080'],
    answer: 2,
    explanation: 'O RDP, usado para acesso a áreas de trabalho remotas do Windows, opera na porta TCP 3389.',
  },
  {
    id: 55,
    topicId: 'protocols',
    question: 'Qual protocolo é usado para sincronização de tempo em uma rede?',
    options: ['NTP', 'SNMP', 'TELNET', 'TFTP'],
    answer: 0,
    explanation: 'O NTP (Network Time Protocol) é usado para sincronizar os relógios de computadores em uma rede com uma fonte de tempo precisa.',
  },
  {
    id: 56,
    topicId: 'protocols',
    question: 'Qual protocolo é usado para gerenciar dispositivos de rede, como roteadores e switches?',
    options: ['SMTP', 'NTP', 'SNMP', 'RDP'],
    answer: 2,
    explanation: 'O SNMP (Simple Network Management Protocol) é usado para monitorar e gerenciar dispositivos em uma rede, coletando informações e configurando parâmetros.',
  },
  {
    id: 57,
    topicId: 'protocols',
    question: 'O SSH (Secure Shell) fornece uma alternativa segura a qual protocolo legado?',
    options: ['FTP', 'HTTP', 'Telnet', 'SMTP'],
    answer: 2,
    explanation: 'O SSH (porta 22) foi projetado para substituir o Telnet (porta 23), fornecendo uma conexão de terminal remoto criptografada e segura.',
  },
  {
    id: 58,
    topicId: 'protocols',
    question: 'Qual o propósito do handshake de três vias do TCP (three-way handshake)?',
    options: ['Negociar o tamanho da janela de congestionamento', 'Estabelecer uma conexão confiável', 'Encerrar uma conexão', 'Resolver um endereço IP'],
    answer: 1,
    explanation: 'O handshake de três vias (SYN, SYN-ACK, ACK) é usado pelo TCP para estabelecer uma conexão confiável e sincronizar os números de sequência entre o cliente e o servidor antes da transferência de dados.',
  },
  {
    id: 59,
    topicId: 'protocols',
    question: 'Qual protocolo é usado para recuperar e-mails de um servidor, geralmente excluindo-os do servidor após o download?',
    options: ['IMAP', 'SMTP', 'POP3', 'HTTP'],
    answer: 2,
    explanation: 'O POP3 (Post Office Protocol version 3) é projetado para baixar e-mails de um servidor para um único cliente e, em seguida, geralmente excluí-los do servidor.',
  },
  {
    id: 60,
    topicId: 'protocols',
    question: 'O que o DNS faz?',
    options: ['Transfere arquivos', 'Atribui endereços IP', 'Converte nomes de domínio em endereços IP', 'Criptografa a comunicação web'],
    answer: 2,
    explanation: 'O DNS (Domain Name System) funciona como uma "lista telefônica da internet", traduzindo nomes de domínio legíveis por humanos (como www.google.com) em endereços IP numéricos que os computadores usam para se localizar.',
  },
  {
    id: 61,
    topicId: 'protocols',
    question: 'O protocolo TLS/SSL é usado para fornecer segurança a qual protocolo?',
    options: ['FTP', 'UDP', 'HTTP', 'ICMP'],
    answer: 2,
    explanation: 'O TLS (Transport Layer Security) e seu predecessor SSL (Secure Sockets Layer) são usados para criptografar a comunicação HTTP, criando o HTTPS.',
  },
  {
    id: 62,
    topicId: 'protocols',
    question: 'Qual protocolo é mais adequado para streaming de vídeo ao vivo?',
    options: ['TCP', 'UDP', 'FTP', 'SMTP'],
    answer: 1,
    explanation: 'O UDP é preferido para streaming de vídeo ao vivo porque sua baixa sobrecarga e falta de retransmissão permitem uma entrega mais rápida dos pacotes, onde a perda ocasional de um quadro é mais aceitável do que o atraso causado pela retransmissão do TCP.',
  },
  {
    id: 63,
    topicId: 'protocols',
    question: 'Qual protocolo é usado para transferir arquivos de configuração ou imagens de SO para dispositivos de rede de forma simples?',
    options: ['FTP', 'SFTP', 'TFTP', 'HTTP'],
    answer: 2,
    explanation: 'O TFTP (Trivial File Transfer Protocol) é uma versão simplificada do FTP que usa UDP e não possui autenticação, tornando-o ideal para transferências rápidas e simples em uma rede local, como o boot de dispositivos.',
  },
  {
    id: 64,
    topicId: 'protocols',
    question: 'O IMAP (Internet Message Access Protocol) difere do POP3 porque:',
    options: ['O IMAP envia e-mails, enquanto o POP3 recebe', 'O IMAP armazena e-mails no servidor, permitindo o acesso de múltiplos clientes', 'O IMAP é menos seguro que o POP3', 'O IMAP é um protocolo mais antigo'],
    answer: 1,
    explanation: 'A principal diferença é que o IMAP mantém os e-mails no servidor e sincroniza o estado (lido, não lido, etc.) entre múltiplos clientes, enquanto o POP3 geralmente baixa os e-mails para um único cliente.',
  },
  // Devices - 20 questions
  {
    id: 8,
    topicId: 'devices',
    question: 'Um dispositivo que conecta vários computadores em uma única LAN e opera na Camada 2 é chamado de...?',
    options: ['Hub', 'Roteador', 'Switch', 'Modem'],
    answer: 2,
    explanation: 'Um switch é um dispositivo da Camada 2 que usa endereços MAC para encaminhar dados para dispositivos específicos em uma rede local (LAN), melhorando a eficiência em relação a um hub.',
  },
  {
    id: 9,
    topicId: 'devices',
    question: 'Qual dispositivo é usado para conectar redes diferentes e toma decisões de roteamento com base em endereços IP?',
    options: ['Switch', 'Roteador', 'Bridge', 'Repetidor'],
    answer: 1,
    explanation: 'Um roteador é um dispositivo da Camada 3 que conecta duas ou mais redes diferentes. Ele usa endereços IP para determinar o melhor caminho para encaminhar pacotes entre essas redes.',
  },
  {
    id: 65,
    topicId: 'devices',
    question: 'Qual dispositivo simplesmente repete um sinal elétrico para estender o alcance de uma rede?',
    options: ['Hub', 'Repetidor', 'Bridge', 'Roteador'],
    answer: 1,
    explanation: 'Um repetidor opera na Camada 1 (Física) e regenera o sinal para combater a atenuação, permitindo que o cabo da rede se estenda por distâncias maiores.',
  },
  {
    id: 66,
    topicId: 'devices',
    question: 'Qual dispositivo cria múltiplos domínios de colisão, mas apenas um domínio de broadcast?',
    options: ['Hub', 'Switch', 'Roteador', 'Repetidor'],
    answer: 1,
    explanation: 'Um switch cria um domínio de colisão separado para cada porta, mas todas as portas em um switch (por padrão) pertencem ao mesmo domínio de broadcast. Os roteadores quebram os domínios de broadcast.',
  },
  {
    id: 67,
    topicId: 'devices',
    question: 'Um Access Point (AP) sem fio opera principalmente em qual camada do modelo OSI?',
    options: ['Camada 3', 'Camada 2', 'Camada 1', 'Camada 4'],
    answer: 1,
    explanation: 'Um Access Point é essencialmente uma bridge que conecta dispositivos sem fio a uma rede com fio, operando principalmente na Camada 2 (Enlace de Dados) ao usar endereços MAC.',
  },
  {
    id: 68,
    topicId: 'devices',
    question: 'O que é um firewall?',
    options: ['Um dispositivo para aumentar a velocidade da rede', 'Um dispositivo que modula e demodula sinais', 'Um sistema de segurança que monitora e controla o tráfego de rede', 'Um dispositivo para armazenar dados da rede'],
    answer: 2,
    explanation: 'Um firewall é um dispositivo ou software de segurança de rede que impõe regras para permitir ou bloquear o tráfego de entrada e saída, protegendo a rede interna.',
  },
  {
    id: 69,
    topicId: 'devices',
    question: 'Um Hub opera em qual camada do modelo OSI?',
    options: ['Camada 1 (Física)', 'Camada 2 (Enlace de Dados)', 'Camada 3 (Rede)', 'Nenhuma das anteriores'],
    answer: 0,
    explanation: 'Um hub é um dispositivo simples da Camada 1. Ele recebe um sinal em uma porta e o retransmite para todas as outras portas, criando um único domínio de colisão e broadcast.',
  },
  {
    id: 70,
    topicId: 'devices',
    question: 'Qual a diferença entre um switch gerenciável e um não gerenciável?',
    options: ['Switches gerenciáveis são mais rápidos', 'Switches não gerenciáveis não usam endereços MAC', 'Switches gerenciáveis oferecem recursos de configuração, como VLANs e QoS', 'Switches não gerenciáveis não podem conectar mais de 4 dispositivos'],
    answer: 2,
    explanation: 'Switches gerenciáveis permitem que administradores configurem, monitorem e gerenciem a rede, com suporte a recursos como VLANs, Spanning Tree Protocol (STP) e Quality of Service (QoS).',
  },
  {
    id: 71,
    topicId: 'devices',
    question: 'Qual dispositivo é usado para converter sinais digitais em sinais analógicos para transmissão por linhas telefônicas e vice-versa?',
    options: ['Roteador', 'Modem', 'Switch', 'Hub'],
    answer: 1,
    explanation: 'Um Modem (Modulador-Demodulador) converte os sinais digitais de um computador em sinais analógicos para viajar pela linha telefônica e faz o processo inverso no destino.',
  },
  {
    id: 72,
    topicId: 'devices',
    question: 'Um "roteador de borda" (edge router) está localizado onde?',
    options: ['No centro da rede interna', 'Conectando dois switches', 'Na fronteira entre a rede interna (LAN) e uma rede externa (WAN), como a Internet', 'Apenas em redes domésticas'],
    answer: 2,
    explanation: 'Um roteador de borda fica na periferia da rede de uma organização, atuando como o gateway para a Internet ou outras redes externas.',
  },
  {
    id: 73,
    topicId: 'devices',
    question: 'O que é um switch de Camada 3?',
    options: ['Um switch que opera apenas na Camada 3', 'Um roteador com muitas portas', 'Um switch que pode executar algumas funções de roteamento, como roteamento entre VLANs', 'Um nome mais antigo para um hub'],
    answer: 2,
    explanation: 'Um switch de Camada 3 (ou switch multicamada) é um dispositivo híbrido que combina as funções de um switch (encaminhamento rápido na Camada 2) e um roteador (decisões de roteamento na Camada 3).',
  },
  {
    id: 74,
    topicId: 'devices',
    question: 'Qual dispositivo de rede é projetado para filtrar e encaminhar pacotes entre segmentos de LAN diferentes?',
    options: ['Repetidor', 'Hub', 'Bridge', 'Modem'],
    answer: 2,
    explanation: 'Uma bridge é um dispositivo da Camada 2 que conecta dois ou mais segmentos de LAN e usa endereços MAC para tomar decisões de encaminhamento, ajudando a isolar o tráfego.',
  },
  {
    id: 75,
    topicId: 'devices',
    question: 'Em que cenário um roteador seria necessário em vez de um switch?',
    options: ['Para conectar 10 computadores no mesmo escritório', 'Para conectar dois departamentos em redes IP diferentes (ex: Vendas e Marketing)', 'Para estender um sinal de rede por mais 50 metros', 'Para criar uma pequena rede doméstica com 3 computadores'],
    answer: 1,
    explanation: 'Os roteadores são necessários para comunicar entre redes IP diferentes (sub-redes). Os switches operam dentro de uma única rede IP.',
  },
  {
    id: 76,
    topicId: 'devices',
    question: 'Qual dispositivo armazena uma tabela de endereços MAC para mapear portas a dispositivos?',
    options: ['Hub', 'Roteador', 'Switch', 'Repetidor'],
    answer: 2,
    explanation: 'Um switch aprende os endereços MAC dos dispositivos conectados a cada uma de suas portas e armazena essas informações em uma tabela CAM (Content Addressable Memory) para encaminhar o tráfego de forma eficiente.',
  },
  {
    id: 77,
    topicId: 'devices',
    question: 'O que é um balanceador de carga (load balancer)?',
    options: ['Um dispositivo que aumenta a voltagem da rede', 'Um dispositivo que distribui o tráfego de rede entre vários servidores', 'Um tipo de firewall', 'Um dispositivo que traduz endereços IP'],
    answer: 1,
    explanation: 'Um balanceador de carga distribui solicitações de clientes entre um grupo de servidores (um "farm" de servidores) para otimizar a utilização de recursos, maximizar o rendimento e minimizar o tempo de resposta.',
  },
  {
    id: 78,
    topicId: 'devices',
    question: 'Um Network Interface Card (NIC) opera principalmente em quais camadas OSI?',
    options: ['Camada 3 e 4', 'Camada 1 e 2', 'Apenas Camada 1', 'Apenas Camada 3'],
    answer: 1,
    explanation: 'Uma placa de rede (NIC) é responsável por colocar os bits no meio físico (Camada 1) e também lida com o endereçamento MAC e enquadramento (Camada 2).',
  },
  {
    id: 79,
    topicId: 'devices',
    question: 'Um roteador quebra qual tipo de domínio?',
    options: ['Domínio de colisão', 'Domínio de broadcast', 'Ambos', 'Nenhum'],
    answer: 2,
    explanation: 'Cada porta de um roteador é um domínio de broadcast separado. Os roteadores são usados para segmentar redes e controlar o tráfego de broadcast. Os switches quebram domínios de colisão.',
  },
  {
    id: 80,
    topicId: 'devices',
    question: 'O que é um proxy server?',
    options: ['Um servidor que atribui endereços IP', 'Um servidor que atua como intermediário para solicitações de clientes buscando recursos de outros servidores', 'Um servidor de arquivos', 'Um servidor que hospeda sites'],
    answer: 1,
    explanation: 'Um servidor proxy atua como um gateway entre os usuários e a internet, encaminhando as solicitações dos clientes e retornando as respostas dos servidores. Ele pode ser usado para segurança, cache e anonimato.',
  },
  {
    id: 81,
    topicId: 'devices',
    question: 'Onde um IDS (Intrusion Detection System) se encaixa em uma topologia de rede?',
    options: ['Substitui o roteador', 'Fica "fora de banda", monitorando uma cópia do tráfego', 'Substitui o switch', 'Conecta diretamente os computadores'],
    answer: 1,
    explanation: 'Um IDS geralmente opera de forma passiva, conectado a uma porta espelhada (SPAN) de um switch. Ele analisa uma cópia do tráfego para detectar atividades maliciosas sem estar no caminho direto dos dados.',
  },
  {
    id: 82,
    topicId: 'devices',
    question: 'Qual dispositivo usa NAT (Network Address Translation) para permitir que múltiplos dispositivos em uma LAN usem um único endereço IP público?',
    options: ['Switch', 'Hub', 'Roteador', 'Access Point'],
    answer: 2,
    explanation: 'O NAT é uma função tipicamente executada por roteadores (especialmente roteadores domésticos e de borda) para traduzir endereços IP privados em um único endereço IP público, conservando endereços IP e ocultando a rede interna.',
  },
  // Security - 20 questions
  {
    id: 10,
    topicId: 'security',
    question: 'Qual dos seguintes é um tipo comum de firewall que monitora o estado das conexões ativas?',
    options: ['Firewall de filtragem de pacotes', 'Firewall de proxy', 'Firewall de inspeção de estado', 'Firewall de próxima geração'],
    answer: 2,
    explanation: 'Um firewall de inspeção de estado rastreia o estado das conexões de rede e toma decisões com base no contexto da conexão, oferecendo mais segurança do que um simples firewall de filtragem de pacotes.',
  },
  {
    id: 11,
    topicId: 'security',
    question: 'O que significa "VPN"?',
    options: ['Rede Privada Virtual', 'Rede Muito Privada', 'Rede Pública Virtual', 'Rede Privada Verificada'],
    answer: 0,
    explanation: 'VPN significa Rede Privada Virtual. Ela cria uma conexão segura e criptografada em uma rede menos segura, como a internet pública.',
  },
  {
    id: 83,
    topicId: 'security',
    question: 'Qual tipo de ataque envolve o envio de um grande volume de tráfego para sobrecarregar um serviço ou rede?',
    options: ['Phishing', 'Man-in-the-Middle', 'DDoS (Distributed Denial of Service)', 'Ransomware'],
    answer: 2,
    explanation: 'Um ataque DDoS usa múltiplos sistemas comprometidos para inundar um alvo com tráfego, tornando o serviço indisponível para usuários legítimos.',
  },
  {
    id: 84,
    topicId: 'security',
    question: 'O que é a "tríade da CIA" na segurança da informação?',
    options: ['Criptografia, Integridade, Acesso', 'Confidencialidade, Integridade, Autenticação', 'Confidencialidade, Integridade, Disponibilidade', 'Controle, Inspeção, Acesso'],
    answer: 2,
    explanation: 'A tríade da CIA é um modelo fundamental que representa os três pilares da segurança: Confidencialidade (manter os dados secretos), Integridade (garantir que os dados não foram alterados) e Disponibilidade (garantir que os dados e serviços estejam acessíveis).',
  },
  {
    id: 85,
    topicId: 'security',
    question: 'Qual tecnologia é usada para criar zonas desmilitarizadas (DMZs)?',
    options: ['Switches', 'Roteadores', 'Firewalls', 'Hubs'],
    answer: 2,
    explanation: 'Firewalls são usados para criar uma DMZ, que é uma sub-rede isolada entre a rede interna de uma organização e a internet pública, hospedando serviços externos como servidores web.',
  },
  {
    id: 86,
    topicId: 'security',
    question: 'O que é um ataque de phishing?',
    options: ['Um ataque que explora uma vulnerabilidade de software', 'Uma tentativa de enganar usuários para que revelem informações confidenciais, como senhas e dados de cartão de crédito', 'Um ataque que intercepta a comunicação entre duas partes', 'Um ataque que bloqueia o acesso a um sistema'],
    answer: 1,
    explanation: 'Phishing é uma forma de engenharia social onde um atacante se passa por uma entidade confiável (como um banco) em uma comunicação eletrônica para obter informações sensíveis.',
  },
  {
    id: 87,
    topicId: 'security',
    question: 'Qual é a principal função de um IPS (Intrusion Prevention System)?',
    options: ['Apenas detectar ataques', 'Detectar e tentar bloquear ativamente os ataques em tempo real', 'Criptografar o tráfego da rede', 'Autenticar usuários'],
    answer: 1,
    explanation: 'Diferente de um IDS (que apenas detecta e alerta), um IPS é colocado "em linha" no tráfego da rede e pode tomar medidas ativas para bloquear atividades maliciosas detectadas.',
  },
  {
    id: 88,
    topicId: 'security',
    question: 'O protocolo WPA2/WPA3 é usado para proteger qual tipo de rede?',
    options: ['Redes com fio (Ethernet)', 'Redes de armazenamento (SAN)', 'Redes de longa distância (WAN)', 'Redes sem fio (Wi-Fi)'],
    answer: 3,
    explanation: 'WPA2 (Wi-Fi Protected Access 2) e seu sucessor WPA3 são protocolos de segurança usados para proteger redes sem fio, fornecendo criptografia e autenticação.',
  },
  {
    id: 89,
    topicId: 'security',
    question: 'O que é MAC Filtering em uma rede sem fio?',
    options: ['Uma forma de criptografia', 'Uma lista de controle de acesso que permite ou nega o acesso à rede com base no endereço MAC do dispositivo', 'Um método para alterar o endereço MAC de um dispositivo', 'Um protocolo para resolver endereços IP'],
    answer: 1,
    explanation: 'A filtragem de MAC é uma medida de segurança que permite que apenas dispositivos com endereços MAC pré-aprovados se conectem a uma rede. No entanto, é considerada uma segurança fraca, pois os endereços MAC podem ser falsificados.',
  },
  {
    id: 90,
    topicId: 'security',
    question: 'O termo "hardening" no contexto de segurança de rede refere-se a:',
    options: ['Tornar os cabos de rede mais fortes', 'Aumentar a velocidade da rede', 'Reduzir a superfície de ataque de um sistema, desativando serviços e portas desnecessários', 'Instalar mais firewalls'],
    answer: 2,
    explanation: 'Hardening é o processo de proteger um sistema, eliminando potenciais vulnerabilidades. Isso inclui remover software desnecessário, alterar senhas padrão e aplicar as configurações de segurança mais rigorosas.',
  },
  {
    id: 91,
    topicId: 'security',
    question: 'Qual é um exemplo de autenticação de dois fatores (2FA)?',
    options: ['Usar uma senha e um PIN', 'Digitar a senha duas vezes', 'Usar uma senha e um código de uso único de um aplicativo no celular', 'Usar duas senhas diferentes'],
    answer: 2,
    explanation: '2FA requer duas formas de verificação de identidades diferentes: algo que você sabe (senha), algo que você tem (celular, token) ou algo que você é (biometria). Senha + código do celular é um exemplo clássico.',
  },
  {
    id: 92,
    topicId: 'security',
    question: 'O que é um ataque "Man-in-the-Middle" (MitM)?',
    options: ['Um ataque de negação de serviço', 'Um ataque onde o atacante secretamente intercepta e possivelmente altera a comunicação entre duas partes', 'Um e-mail fraudulento', 'Um vírus de computador'],
    answer: 1,
    explanation: 'Em um ataque MitM, o atacante se posiciona entre duas vítimas que acreditam estar se comunicando diretamente, permitindo que ele leia, insira e modifique mensagens.',
  },
  {
    id: 93,
    topicId: 'security',
    question: 'Qual das seguintes opções ajuda a garantir a integridade dos dados?',
    options: ['Criptografia AES', 'Funções de hash (por exemplo, SHA-256)', 'VPN', 'Autenticação'],
    answer: 1,
    explanation: 'As funções de hash criam uma "impressão digital" única para os dados. Se os dados forem alterados, o hash também mudará, o que permite verificar a integridade dos dados.',
  },
  {
    id: 94,
    topicId: 'security',
    question: 'Qual política de segurança de firewall é geralmente considerada a mais segura?',
    options: ['Permitir tudo por padrão, negar especificamente', 'Negar tudo por padrão, permitir especificamente', 'Permitir todo o tráfego de entrada, negar todo o de saída', 'Permitir todo o tráfego interno'],
    answer: 1,
    explanation: 'A abordagem de "negação implícita" ou "negar tudo por padrão" é a mais segura. Ela bloqueia todo o tráfego, exceto aquele que foi explicitamente permitido por uma regra.',
  },
  {
    id: 95,
    topicId: 'security',
    question: 'O que o Port Knocking faz?',
    options: ['Desativa portas permanentemente', 'Abre portas em um firewall apenas após uma sequência correta de tentativas de conexão a portas fechadas', 'Testa todas as portas para ver quais estão abertas', 'Muda os números das portas dinamicamente'],
    answer: 1,
    explanation: 'Port Knocking é um método para controlar o acesso a portas, exigindo que um cliente faça tentativas de conexão a uma série de portas pré-definidas na ordem correta antes que a porta real seja aberta.',
  },
  {
    id: 96,
    topicId: 'security',
    question: 'O que é um honeypot?',
    options: ['Um servidor de alta segurança', 'Um sistema de computador chamariz, configurado para atrair e prender atacantes', 'Uma senha muito forte', 'Um tipo de criptografia'],
    answer: 1,
    explanation: 'Um honeypot é um mecanismo de segurança que cria uma armadilha para atacantes. Ele imita um sistema real para atrair ciberataques, permitindo que os defensores estudem as táticas dos atacantes e desviem sua atenção de sistemas reais.',
  },
  {
    id: 97,
    topicId: 'security',
    question: 'O que é um "Zero-Day Exploit"?',
    options: ['Um ataque que acontece no primeiro dia do ano', 'Um ataque que explora uma vulnerabilidade de software que é desconhecida pelo fornecedor', 'Um ataque que leva zero segundos para ser executado', 'Um ataque que não deixa rastros'],
    answer: 1,
    explanation: 'Uma vulnerabilidade ou ataque "zero-day" é aquele que o fornecedor do software ainda não conhece ou para o qual ainda não lançou um patch, tornando-o particularmente perigoso.',
  },
  {
    id: 98,
    topicId: 'security',
    question: 'Qual é o propósito do 802.1X?',
    options: ['Acelerar as conexões Wi-Fi', 'Fornecer um padrão para controle de acesso à rede baseado em portas', 'Criptografar discos rígidos', 'Gerenciar endereços IP'],
    answer: 1,
    explanation: 'O IEEE 802.1X é um padrão que fornece um mecanismo de autenticação para dispositivos que desejam se conectar a uma LAN ou WLAN. Ele força a autenticação do dispositivo antes de permitir o acesso à rede.',
  },
  {
    id: 99,
    topicId: 'security',
    question: 'Qual tipo de malware se espalha por redes de computadores explorando vulnerabilidades de forma autônoma?',
    options: ['Vírus', 'Cavalo de Troia (Trojan)', 'Worm', 'Spyware'],
    answer: 2,
    explanation: 'Um worm é um tipo de malware que se replica para se espalhar para outros computadores em uma rede, geralmente sem intervenção humana, explorando falhas de segurança.',
  },
  {
    id: 100,
    topicId: 'security',
    question: 'Qual das seguintes é uma boa prática para segurança de senhas?',
    options: ['Usar a mesma senha para vários serviços', 'Usar senhas curtas e fáceis de lembrar', 'Usar uma combinação de letras maiúsculas e minúsculas, números e símbolos', 'Anotar a senha em um post-it no monitor'],
    answer: 2,
    explanation: 'Senhas fortes são longas e complexas, misturando diferentes tipos de caracteres, para dificultar ataques de força bruta ou de dicionário.',
  },
];


export const weeklyProgress = [
  { week: 'Semana 1', points: 150 },
  { week: 'Semana 2', points: 220 },
  { week: 'Semana 3', points: 180 },
  { week: 'Semana 4', points: 350 },
];
